const mongoose = require("mongoose");
const Category = require("../models/Category"); // Adjust the path accordingly
const Subcategory = require("../models/Subcategory"); // Adjust the path accordingly
const Product = require("../models/Product"); // Adjust the path accordingly

// Connect to MongoDB
mongoose
  .connect("mongodb://localhost:27017/shopping-kart", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log("MongoDB connected");
    seedDatabase();
  })
  .catch((err) => {
    console.error("MongoDB connection error:", err);
  });

// Dummy categories data for Men, Women, and Children
const data = [
  {
    CategoryName: "Men",
    Description: "Bag, Watch, Perfume, and Sunglasses for men.",
    ImageURL: "men",
    IsActive: true,
    subcategories: [
      {
        SubcategoryName: "Bag",
        Description: "Men's bags including backpacks and messenger bags.",
        ImageURL: "men-bag",
        IsActive: true,
        categories: [
          {
            ProductName: "Men's Backpack",
            Price: 400,
            StockQuantity: 100,
            Description: "Stylish and functional backpack for daily use.",
            ImageURLs: [
              "men-bag1-Men'sBackpack1",
              "men-bag1-Men'sBackpack2",
              "men-bag1-Men'sBackpack3",
              "men-bag1-Men'sBackpack4",
            ],
            SKU: "MB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand A",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Messenger Bag",
            Price: 685,
            StockQuantity: 80,
            Description: "Stylish messenger bag for work and travel.",
            ImageURLs: [
              "men-bag2-Men'sMessengerBag1",
              "men-bag2-Men'sMessengerBag",
              "men-bag2-Men'sMessengerBag3",
              "men-bag2-Men'sMessengerBag4",
            ],
            SKU: "MMB-001",
            IsActive: true,
            ProductType: "Messenger Bag",
            Brand: "Brand B",
            Color: "Brown",
            Size: "N/A",
            Featured: false,
          },
          // Additional dummy products
          {
            ProductName: "Men's Duffle Bag",
            Price: 599,
            StockQuantity: 50,
            Description: "Spacious duffle bag for gym and travel.",
            ImageURLs: [
              "men-bag3-Men'sDuffleBag1",
              "men-bag3-Men'sDuffleBag2",
              "men-bag3-Men'sDuffleBag3",
              "men-bag3-Men'sDuffleBag4",
            ],
            SKU: "MDB-001",
            IsActive: true,
            ProductType: "Duffle Bag",
            Brand: "Brand C",
            Color: "Gray",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Laptop Bag",
            Price: 699,
            StockQuantity: 40,
            Description: "Stylish laptop bag with multiple compartments.",
            ImageURLs: [
              "men-bag4-Men'sLaptopBag1",
              "men-bag4-Men'sLaptopBag2",
              "men-bag4-Men'sLaptopBag3",
              "men-bag4-Men'sLaptopBag4",
            ],
            SKU: "MLB-001",
            IsActive: true,
            ProductType: "Laptop Bag",
            Brand: "Brand D",
            Color: "Navy",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Crossbody Bag",
            Price: 399,
            StockQuantity: 70,
            Description: "Compact crossbody bag for essentials.",
            ImageURLs: [
              "men-bag5-Men'sCrossbodyBag1",
              "men-bag5-Men'sCrossbodyBag2",
              "men-bag5-Men'sCrossbodyBag3",
              "men-bag5-Men'sCrossbodyBag4",
            ],
            SKU: "MCB-001",
            IsActive: true,
            ProductType: "Crossbody Bag",
            Brand: "Brand E",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Travel Bag",
            Price: 799,
            StockQuantity: 30,
            Description: "Durable travel bag for weekend getaways.",
            ImageURLs: [
              "men-bag6-Men'sTravelBag1",
              "men-bag6-Men'sTravelBag2",
              "men-bag6-Men'sTravelBag3",
              "men-bag6-Men'sTravelBag4",
            ],
            SKU: "MTB-001",
            IsActive: true,
            ProductType: "Travel Bag",
            Brand: "Brand F",
            Color: "Olive",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Waterproof Laptop Bag",
            Price: 599,
            StockQuantity: 50,
            Description: "Waterproof bag designed to protect your laptop.",
            ImageURLs: [
              "men-bag7-Men'sWaterproofLaptopBag1",
              "men-bag7-Men'sWaterproofLaptopBag2",
              "men-bag7-Men'sWaterproofLaptopBag3",
              "men-bag7-Men'sWaterproofLaptopBag4",
            ],
            SKU: "MWLB-001",
            IsActive: true,
            ProductType: "Laptop Bag",
            Brand: "Brand H",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Vintage Leather Backpack",
            Price: 899,
            StockQuantity: 40,
            Description: "Stylish vintage leather backpack for a classic look.",
            ImageURLs: [
              "men-bag8-Men'sVintageLeatherBackpack1",
              "men-bag8-Men'sVintageLeatherBackpack2",
              "men-bag8-Men'sVintageLeatherBackpack3",
              "men-bag8-Men'sVintageLeatherBackpack4",
            ],
            SKU: "MVLB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand G",
            Color: "Tan",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Gym Bag",
            Price: 1340,
            StockQuantity: 60,
            Description: "Lightweight gym bag for workouts.",
            ImageURLs: [
              "men-bag9-Men'sGymBag1",
              "men-bag9-Men'sGymBag2",
              "men-bag9-Men'sGymBag3",
              "men-bag9-Men'sGymBag4",
            ],
            SKU: "MGB-001",
            IsActive: true,
            ProductType: "Gym Bag",
            Brand: "Brand G",
            Color: "Red",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Leather Messenger Bag",
            Price: 890,
            StockQuantity: 50,
            Description: "Stylish leather messenger bag for work and travel.",
            ImageURLs: [
              "men-bag10-Men'sLeatherMessengerBag1",
              "men-bag10-Men'sLeatherMessengerBag2",
              "men-bag10-Men'sLeatherMessengerBag3",
              "men-bag10-Men'sLeatherMessengerBag4",
            ],
            SKU: "MLMB-001",
            IsActive: true,
            ProductType: "Messenger Bag",
            Brand: "Brand A",
            Color: "Brown",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Business Briefcase",
            Price: 990,
            StockQuantity: 20,
            Description: "Elegant briefcase for professional settings.",
            ImageURLs: [
              "men-bag11-Men'sBusinessBriefcase1",
              "men-bag11-Men'sBusinessBriefcase2",
              "men-bag11-Men'sBusinessBriefcase3",
              "men-bag11-Men'sBusinessBriefcase4",
            ],
            SKU: "MBB-001",
            IsActive: true,
            ProductType: "Briefcase",
            Brand: "Brand E",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Canvas Backpack",
            Price: 550,
            StockQuantity: 100,
            Description: "Durable canvas backpack for everyday use.",
            ImageURLs: [
              "men-bag12-Men'sCanvasBackpack1",
              "men-bag12-Men'sCanvasBackpack2",
              "men-bag12-Men'sCanvasBackpack3",
              "men-bag12-Men'sCanvasBackpack4",
            ],
            SKU: "MCB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand B",
            Color: "Navy",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Sling Bag",
            Price: 750,
            StockQuantity: 90,
            Description: "Casual sling bag for everyday use.",
            ImageURLs: [
              "men-bag13-Men'sSlingBag1",
              "men-bag13-Men'sSlingBag2",
              "men-bag13-Men'sSlingBag3",
              "men-bag13-Men'sSlingBag4",
            ],
            SKU: "MSB-001",
            IsActive: true,
            ProductType: "Sling Bag",
            Brand: "Brand H",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Watch",
        Description: "Men's watches including formal and casual styles.",
        ImageURL: "men-watch",
        IsActive: true,
        categories: [
          {
            ProductName: "Men's Analog Watch",
            Price: 899,
            StockQuantity: 50,
            Description: "Elegant analog watch for formal occasions.",
            ImageURLs: [
              "men-watch1-Men'sAnalogWatch1",
              "men-watch1-Men'sAnalogWatch2",
              "men-watch1-Men'sAnalogWatch3",
              "men-watch1-Men'sAnalogWatch4",
            ],
            SKU: "MAW-001",
            IsActive: true,
            ProductType: "Watch",
            Brand: "Brand C",
            Color: "Silver",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Sports Watch",
            Price: 1530,
            StockQuantity: 30,
            Description: "Durable sports watch for outdoor activities.",
            ImageURLs: [
              "men-watch2-Men'sSportsWatch1",
              "men-watch2-Men'sSportsWatch2",
              "men-watch2-Men'sSportsWatch3",
              "men-watch2-Men'sSportsWatch4",
            ],
            SKU: "MSW-001",
            IsActive: true,
            ProductType: "Watch",
            Brand: "Brand D",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
          // Additional dummy products
          {
            ProductName: "Men's Smart Watch",
            Price: 650,
            StockQuantity: 20,
            Description: "Smart watch with fitness tracking and notifications.",
            ImageURLs: [
              "men-watch3-Men'sSmartWatch1",
              "men-watch3-Men'sSmartWatch2",
              "men-watch3-Men'sSmartWatch3",
              "men-watch3-Men'sSmartWatch4",
            ],
            SKU: "MSW-002",
            IsActive: true,
            ProductType: "Smart Watch",
            Brand: "Brand E",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Leather Strap Watch",
            Price: 829,
            StockQuantity: 25,
            Description:
              "Classic leather strap watch for a sophisticated look.",
            ImageURLs: [
              "men-watch4-Men'sLeatherStrapWatch1",
              "men-watch4-Men'sLeatherStrapWatch2",
              "men-watch4-Men'sLeatherStrapWatch3",
              "men-watch4-Men'sLeatherStrapWatch4",
            ],
            SKU: "MLW-001",
            IsActive: true,
            ProductType: "Watch",
            Brand: "Brand F",
            Color: "Brown",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Digital Watch",
            Price: 485,
            StockQuantity: 100,
            Description: "Digital watch with multiple features.",
            ImageURLs: [
              "men-watch5-Men'sDigitalWatch1",
              "men-watch5-Men'sDigitalWatch2",
              "men-watch5-Men'sDigitalWatch3",
              "men-watch5-Men'sDigitalWatch4",
            ],
            SKU: "MDW-001",
            IsActive: true,
            ProductType: "Digital Watch",
            Brand: "Brand G",
            Color: "Blue",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Chronograph Watch",
            Price: 989,
            StockQuantity: 15,
            Description:
              "Stylish chronograph watch for sports and casual wear.",
            ImageURLs: [
              "men-watch6-Men'sChronographWatch1",
              "men-watch6-Men'sChronographWatch2",
              "men-watch6-Men'sChronographWatch3",
              "men-watch6-Men'sChronographWatch4",
            ],
            SKU: "MCW-001",
            IsActive: true,
            ProductType: "Chronograph Watch",
            Brand: "Brand H",
            Color: "Silver",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Classic Dress Watch",
            Price: 870,
            StockQuantity: 40,
            Description: "A timeless classic dress watch for formal occasions.",
            ImageURLs: [
              "men-watch7-Men'sClassicDressWatch1",
              "men-watch7-Men'sClassicDressWatch2",
              "men-watch7-Men'sClassicDressWatch3",
              "men-watch7-Men'sClassicDressWatch4",
            ],
            SKU: "MCDW-001",
            IsActive: true,
            ProductType: "Dress Watch",
            Brand: "Brand A",
            Color: "Gold",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Casual Leather Watch",
            Price: 1250,
            StockQuantity: 60,
            Description: "Casual leather watch perfect for everyday wear.",
            ImageURLs: [
              "men-watch8-Men'sCasualLeatherWatch1",
              "men-watch8-Men'sCasualLeatherWatch2",
              "men-watch8-Men'sCasualLeatherWatch3",
              "men-watch8-Men'sCasualLeatherWatch4",
            ],
            SKU: "MCLW-001",
            IsActive: true,
            ProductType: "Leather Watch",
            Brand: "Brand B",
            Color: "Brown",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Military Style Watch",
            Price: 999,
            StockQuantity: 30,
            Description: "Rugged military style watch with durable features.",
            ImageURLs: [
              "men-watch9-Men'sMilitaryStyleWatch1",
              "men-watch9-Men'sMilitaryStyleWatch2",
              "men-watch9-Men'sMilitaryStyleWatch3",
              "men-watch9-Men'sMilitaryStyleWatch4",
            ],
            SKU: "MMW-001",
            IsActive: true,
            ProductType: "Military Watch",
            Brand: "Brand C",
            Color: "Green",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Automatic Watch",
            Price: 1383,
            StockQuantity: 15,
            Description: "Luxury automatic watch with intricate design.",
            ImageURLs: [
              "men-watch10-Men'sAutomaticWatch1",
              "men-watch10-Men'sAutomaticWatch2",
              "men-watch10-Men'sAutomaticWatch3",
              "men-watch10-Men'sAutomaticWatch4",
            ],
            SKU: "MAW-002",
            IsActive: true,
            ProductType: "Automatic Watch",
            Brand: "Brand D",
            Color: "Silver",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Diver's Watch",
            Price: 599,
            StockQuantity: 20,
            Description:
              "Water-resistant diver's watch for underwater adventures.",
            ImageURLs: [
              "men-watch11-Men'sDiver'sWatch1",
              "men-watch11-Men'sDiver'sWatch2",
              "men-watch11-Men'sDiver'sWatch3",
              "men-watch11-Men'sDiver'sWatch4",
            ],
            SKU: "MDW-002",
            IsActive: true,
            ProductType: "Diver's Watch",
            Brand: "Brand E",
            Color: "Blue",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Smart Fitness Watch",
            Price: 567,
            StockQuantity: 25,
            Description: "Smart fitness watch with health tracking features.",
            ImageURLs: [
              "men-watch12-Men'sSmartFitnessWatch1",
              "men-watch12-Men'sSmartFitnessWatch2",
              "men-watch12-Men'sSmartFitnessWatch3",
              "men-watch12-Men'sSmartFitnessWatch4",
            ],
            SKU: "MSFW-001",
            IsActive: true,
            ProductType: "Smart Watch",
            Brand: "Brand F",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Vintage Style Watch",
            Price: 588,
            StockQuantity: 50,
            Description: "Vintage style watch with a retro design.",
            ImageURLs: [
              "men-watch13-Men'sVintageStyleWatch1",
              "men-watch13-Men'sVintageStyleWatch2",
              "men-watch13-Men'sVintageStyleWatch3",
              "men-watch13-Men'sVintageStyleWatch4",
            ],
            SKU: "MVW-001",
            IsActive: true,
            ProductType: "Vintage Watch",
            Brand: "Brand G",
            Color: "Bronze",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Chronograph Sports Watch",
            Price: 784,
            StockQuantity: 35,
            Description:
              "Stylish chronograph sports watch for active lifestyles.",
            ImageURLs: [
              "men-watch14-Men'sChronographSportsWatch1",
              "men-watch14-Men'sChronographSportsWatch2",
              "men-watch14-Men'sChronographSportsWatch3",
              "men-watch14-Men'sChronographSportsWatch4",
            ],
            SKU: "MCSW-001",
            IsActive: true,
            ProductType: "Chronograph Watch",
            Brand: "Brand H",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Perfume",
        Description: "Men's perfumes and fragrances.",
        ImageURL: "men-perfume",
        IsActive: true,
        categories: [
          {
            ProductName: "Men's Eau de Parfum",
            Price: 799,
            StockQuantity: 30,
            Description: "Long-lasting eau de parfum for special occasions.",
            ImageURLs: [
              "men-perfume1-Men'sEaudeParfum1",
              "men-perfume1-Men'sEaudeParfum2",
              "men-perfume1-Men'sEaudeParfum3",
              "men-perfume1-Men'sEaudeParfum4",
            ],
            SKU: "MEP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand D",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },
          {
            ProductName: "Men's Sport Fragrance",
            Price: 395,
            StockQuantity: 70,
            Description: "Energetic fragrance for an active lifestyle.",
            ImageURLs: [
              "men-perfume2-Men'sSportFragrance1",
              "men-perfume2-Men'sSportFragrance2",
              "men-perfume2-Men'sSportFragrance3",
              "men-perfume2-Men'sSportFragrance4",
            ],
            SKU: "MSF-001",
            IsActive: true,
            ProductType: "Sport Fragrance",
            Brand: "Brand E",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },
          {
            ProductName: "Men's Woodsy Scent",
            Price: 872,
            StockQuantity: 20,
            Description: "Rich woodsy scent for a bold statement.",
            ImageURLs: [
              "men-perfume3-Men'sWoodsyScent1",
              "men-perfume3-Men'sWoodsyScent2",
              "men-perfume3-Men'sWoodsyScent3",
              "men-perfume3-Men'sWoodsyScent4",
            ],
            SKU: "MWS-001",
            IsActive: true,
            ProductType: "Eau de Toilette",
            Brand: "Brand F",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },

          {
            ProductName: "Men's Night Fragrance",
            Price: 998,
            StockQuantity: 15,
            Description: "Intense fragrance for evening wear.",
            ImageURLs: [
              "men-perfume4-Men'sNightFragrance1",
              "men-perfume4-Men'sNightFragrance2",
              "men-perfume4-Men'sNightFragrance3",
              "men-perfume4-Men'sNightFragrance4",
            ],
            SKU: "MNF-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand H",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },
          {
            ProductName: "Men's Fresh Citrus Cologne",
            Price: 459,
            StockQuantity: 50,
            Description: "A refreshing citrus cologne perfect for daily wear.",
            ImageURLs: [
              "men-perfume5-Men'sFreshCitrusCologne1",
              "men-perfume5-Men'sFreshCitrusCologne2",
              "men-perfume5-Men'sFreshCitrusCologne3",
              "men-perfume5-Men'sFreshCitrusCologne4",
            ],
            SKU: "MFCC-001",
            IsActive: true,
            ProductType: "Cologne",
            Brand: "Brand I",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },
          {
            ProductName: "Men's Spicy Wood Perfume",
            Price: 873,
            StockQuantity: 30,
            Description:
              "A bold and spicy wood fragrance for the adventurous man.",
            ImageURLs: [
              "men-perfume6-Men'sSpicyWoodPerfume1",
              "men-perfume6-Men'sSpicyWoodPerfume2",
              "men-perfume6-Men'sSpicyWoodPerfume3",
              "men-perfume6-Men'sSpicyWoodPerfume4",
            ],
            SKU: "MSWP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand J",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },
          {
            ProductName: "Men's Intense Noir Fragrance",
            Price: 999,
            StockQuantity: 20,
            Description: "A deep and intense fragrance for evening wear.",
            ImageURLs: [
              "men-perfume7-Men'sIntenseNoirFragrance1",
              "men-perfume7-Men'sIntenseNoirFragrance2",
              "men-perfume7-Men'sIntenseNoirFragrance3",
              "men-perfume7-Men'sIntenseNoirFragrance4",
            ],
            SKU: "MINF-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand L",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },
          {
            ProductName: "Men's Royale Blue Eau De Parfum",
            Price: 549,
            StockQuantity: 40,
            Description: "Luxurious oud fragrance",
            ImageURLs: [
              "men-perfume8-Men'sRoyaleBlueEauDeParfum1",
              "men-perfume8-Men'sRoyaleBlueEauDeParfum2",
              "men-perfume8-Men'sRoyaleBlueEauDeParfum3",
              "men-perfume8-Men'sRoyaleBlueEauDeParfum4",
            ],
            SKU: "MHEC-001",
            IsActive: true,
            ProductType: "Cologne",
            Brand: "Brand M",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },
          {
            ProductName: "Men's Classic Oud Perfume",
            Price: 729,
            StockQuantity: 15,
            Description: "Luxurious oud fragrance with rich and warm notes.",
            ImageURLs: [
              "men-perfume9-Men'sClassicOudPerfume1",
              "men-perfume9-Men'sClassicOudPerfume2",
              "men-perfume9-Men'sClassicOudPerfume3",
              "men-perfume9-Men'sClassicOudPerfume4",
            ],
            SKU: "MCOP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand N",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },

          {
            ProductName: "Men's Midnight Musk Perfume",
            Price: 799,
            StockQuantity: 25,
            Description: "A seductive musk fragrance for night outings.",
            ImageURLs: [
              "men-perfume10-Men'sMidnightMuskPerfume1",
              "men-perfume10-Men'sMidnightMuskPerfume2",
              "men-perfume10-Men'sMidnightMuskPerfume3",
              "men-perfume10-Men'sMidnightMuskPerfume4",
            ],
            SKU: "MMP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand P",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Sunglasses",
        Description: "Men's sunglasses for style and protection.",
        ImageURL: "men-sunglasses",
        IsActive: true,
        categories: [
          {
            ProductName: "Men's Aviator Sunglasses",
            Price: 899,
            StockQuantity: 150,
            Description: "Classic aviator sunglasses for a stylish look.",
            ImageURLs: [
              "men-sunglasses1-Men'sAviatorSunglasses1",
              "men-sunglasses1-Men'sAviatorSunglasses2",
              "men-sunglasses1-Men'sAviatorSunglasses3",
              "men-sunglasses1-Men'sAviatorSunglasses4",
            ],
            SKU: "MAS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand A",
            Color: "Gold",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Wayfarer Sunglasses",
            Price: 735,
            StockQuantity: 120,
            Description: "Trendy wayfarer sunglasses for everyday wear.",
            ImageURLs: [
              "men-sunglasses2-Men'sWayfarerSunglasses1",
              "men-sunglasses2-Men'sWayfarerSunglasses2",
              "men-sunglasses2-Men'sWayfarerSunglasses3",
              "men-sunglasses2-Men'sWayfarerSunglasses4",
            ],
            SKU: "MWS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand B",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },

          {
            ProductName: "Men's Round Sunglasses",
            Price: 658,
            StockQuantity: 100,
            Description: "Retro round sunglasses for a vintage look.",
            ImageURLs: [
              "men-sunglasses3-Men'sRoundSunglasses1",
              "men-sunglasses3-Men'sRoundSunglasses2",
              "men-sunglasses3-Men'sRoundSunglasses3",
              "men-sunglasses3-Men'sRoundSunglasses4",
            ],
            SKU: "MRS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand D",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Cat Eye Sunglasses",
            Price: 448,
            StockQuantity: 60,
            Description: "Stylish cat eye sunglasses for a modern twist.",
            ImageURLs: [
              "men-sunglasses4-Men'sCatEyeSunglasses1",
              "men-sunglasses4-Men'sCatEyeSunglasses2",
              "men-sunglasses4-Men'sCatEyeSunglasses3",
              "men-sunglasses4-Men'sCatEyeSunglasses4",
            ],
            SKU: "MCES-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand E",
            Color: "Brown",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Mirrored Sunglasses",
            Price: 585,
            StockQuantity: 40,
            Description: "Trendy mirrored sunglasses for a bold statement.",
            ImageURLs: [
              "men-sunglasses5-Men'sMirroredSunglasses1",
              "men-sunglasses5-Men'sMirroredSunglasses2",
              "men-sunglasses5-Men'sMirroredSunglasses3",
              "men-sunglasses5-Men'sMirroredSunglasses4",
            ],
            SKU: "MMS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand F",
            Color: "Silver",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Oversized Sunglasses",
            Price: 599,
            StockQuantity: 30,
            Description:
              "Fashionable oversized sunglasses for maximum coverage.",
            ImageURLs: [
              "men-sunglasses6-Men'sOversizedSunglasses1",
              "men-sunglasses6-Men'sOversizedSunglasses2",
              "men-sunglasses6-Men'sOversizedSunglasses3",
              "men-sunglasses6-Men'sOversizedSunglasses4",
            ],
            SKU: "MOS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand G",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Vintage Sunglasses",
            Price: 698,
            StockQuantity: 50,
            Description: "Classic vintage sunglasses for a timeless look.",
            ImageURLs: [
              "men-sunglasses7-Men'sVintageSunglasses1",
              "men-sunglasses7-Men'sVintageSunglasses2",
              "men-sunglasses7-Men'sVintageSunglasses3",
              "men-sunglasses7-Men'sVintageSunglasses4",
            ],
            SKU: "MVS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand H",
            Color: "Tortoise",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Classic Black Sunglasses",
            Price: 980,
            StockQuantity: 200,
            Description: "Timeless black sunglasses that go with any outfit.",
            ImageURLs: [
              "men-sunglasses8-Men'sClassicBlackSunglasses1",
              "men-sunglasses8-Men'sClassicBlackSunglasses2",
              "men-sunglasses8-Men'sClassicBlackSunglasses3",
              "men-sunglasses8-Men'sClassicBlackSunglasses4",
            ],
            SKU: "MCBS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand I",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Stylish Square Sunglasses",
            Price: 869,
            StockQuantity: 150,
            Description: "Trendy square sunglasses for a modern look.",
            ImageURLs: [
              "men-sunglasses9-Men'sStylishSquareSunglasses1",
              "men-sunglasses9-Men'sStylishSquareSunglasses2",
              "men-sunglasses9-Men'sStylishSquareSunglasses3",
              "men-sunglasses9-Men'sStylishSquareSunglasses4",
            ],
            SKU: "MSS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand J",
            Color: "Gray",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Retro Pilot Sunglasses",
            Price: 1150,
            StockQuantity: 100,
            Description: "Retro pilot sunglasses for a vintage vibe.",
            ImageURLs: [
              "men-sunglasses10-Men'sRetroPilotSunglasses1",
              "men-sunglasses10-Men'sRetroPilotSunglasses2",
              "men-sunglasses10-Men'sRetroPilotSunglasses3",
              "men-sunglasses10-Men'sRetroPilotSunglasses4",
            ],
            SKU: "MRPS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand K",
            Color: "Gold",
            Size: "N/A",
            Featured: true,
          },

          {
            ProductName: "Men's Fashion Cat Eye Sunglasses",
            Price: 1450,
            StockQuantity: 60,
            Description:
              "Fashion-forward cat eye sunglasses for a bold statement.",
            ImageURLs: [
              "men-sunglasses11-Men'sFashionCatEyeSunglasses1",
              "men-sunglasses11-Men'sFashionCatEyeSunglasses2",
              "men-sunglasses11-Men'sFashionCatEyeSunglasses3",
              "men-sunglasses11-Men'sFashionCatEyeSunglasses4",
            ],
            SKU: "MFCES-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand M",
            Color: "Pink",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Gradient Lens Sunglasses",
            Price: 599,
            StockQuantity: 40,
            Description:
              "Stylish sunglasses with gradient lenses for a chic look.",
            ImageURLs: [
              "men-sunglasses12-Men'sGradientLensSunglasses1",
              "men-sunglasses12-Men'sGradientLensSunglasses2",
              "men-sunglasses12-Men'sGradientLensSunglasses3",
              "men-sunglasses12-Men'sGradientLensSunglasses4",
            ],
            SKU: "MGLS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand N",
            Color: "Brown",
            Size: "N/A",
            Featured: false,
          },

          {
            ProductName: "Men's Designer Oversized Sunglasses",
            Price: 999,
            StockQuantity: 30,
            Description: "Oversized designer sunglasses for a luxurious look.",
            ImageURLs: [
              "men-sunglasses13-Men'sDesignerOversizedSunglasses1",
              "men-sunglasses13-Men'sDesignerOversizedSunglasses2",
              "men-sunglasses13-Men'sDesignerOversizedSunglasses3",
              "men-sunglasses13-Men'sDesignerOversizedSunglasses4",
            ],
            SKU: "MDOS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand P",
            Color: "Tortoise",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
    ],
  },
  {
    CategoryName: "Women",
    Description: "Bags, Watches, Perfumes, and Sunglasses for women.",
    ImageURL: "women",
    IsActive: true,
    subcategories: [
      {
        SubcategoryName: "Bag",
        Description: "Women's bags including handbags and totes.",
        ImageURL: "women-bag",
        IsActive: true,
        categories: [
          {
            ProductName: "Women's Handbag",
            Price: 859,
            StockQuantity: 100,
            Description: "Stylish handbag for everyday use.",
            ImageURLs: [
              "women-bag1-Women'sHandbag1",
              "women-bag1-Women'sHandbag2",
              "women-bag1-Women'sHandbag3",
              "women-bag1-Women'sHandbag4",
            ],
            SKU: "WHB-001",
            IsActive: true,
            ProductType: "Handbag",
            Brand: "Brand A",
            Color: "Beige",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Tote Bag",
            Price: 699,
            StockQuantity: 80,
            Description: "Spacious tote bag for shopping.",
            ImageURLs: [
              "women-bag2-Women'sToteBag1",
              "women-bag2-Women'sToteBag2",
              "women-bag2-Women'sToteBag3",
              "women-bag2-Women'sToteBag4",
            ],
            SKU: "WTB-001",
            IsActive: true,
            ProductType: "Tote Bag",
            Brand: "Brand B",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Crossbody Bag",
            Price: 1239,
            StockQuantity: 120,
            Description: "Compact crossbody bag for essentials.",
            ImageURLs: [
              "women-bag3-Women'sCrossbodyBag1",
              "women-bag3-Women'sCrossbodyBag2",
              "women-bag3-Women'sCrossbodyBag3",
              "women-bag3-Women'sCrossbodyBag4",
            ],
            SKU: "WCB-001",
            IsActive: true,
            ProductType: "Crossbody Bag",
            Brand: "Brand C",
            Color: "Navy",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Backpack",
            Price: 899,
            StockQuantity: 50,
            Description: "Stylish backpack for daily use.",
            ImageURLs: [
              "women-bag4-Women'sBackpack1",
              "women-bag4-Women'sBackpack2",
              "women-bag4-Women'sBackpack3",
              "women-bag4-Women'sBackpack4",
            ],
            SKU: "WBP-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand D",
            Color: "Gray",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Clutch Bag",
            Price: 999,
            StockQuantity: 70,
            Description: "Elegant clutch bag for evening outings.",
            ImageURLs: [
              "women-bag5-Women'sClutchBag1",
              "women-bag5-Women'sClutchBag2",
              "women-bag5-Women'sClutchBag3",
              "women-bag5-Women'sClutchBag4",
            ],
            SKU: "WCB-002",
            IsActive: true,
            ProductType: "Clutch Bag",
            Brand: "Brand E",
            Color: "Red",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Satchel Bag",
            Price: 1399,
            StockQuantity: 40,
            Description: "Chic satchel bag with multiple compartments.",
            ImageURLs: [
              "women-bag6-Women'sSatchelBag1",
              "women-bag6-Women'sSatchelBag2",
              "women-bag6-Women'sSatchelBag3",
              "women-bag6-Women'sSatchelBag4",
            ],
            SKU: "WSB-001",
            IsActive: true,
            ProductType: "Satchel Bag",
            Brand: "Brand F",
            Color: "Brown",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Diaper Bag",
            Price: 899,
            StockQuantity: 30,
            Description: "Functional diaper bag with plenty of storage.",
            ImageURLs: [
              "women-bag7-Women'sDiaperBag1",
              "women-bag7-Women'sDiaperBag2",
              "women-bag7-Women'sDiaperBag3",
              "women-bag7-Women'sDiaperBag4",
            ],
            SKU: "WDB-001",
            IsActive: true,
            ProductType: "Diaper Bag",
            Brand: "Brand G",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Bucket Bag",
            Price: 599,
            StockQuantity: 60,
            Description: "Trendy bucket bag for a casual look.",
            ImageURLs: [
              "women-bag8-Women'sBucketBag1",
              "women-bag8-Women'sBucketBag2",
              "women-bag8-Women'sBucketBag3",
              "women-bag8-Women'sBucketBag4",
            ],
            SKU: "WBB-001",
            IsActive: true,
            ProductType: "Bucket Bag",
            Brand: "Brand H",
            Color: "Tan",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Leather Tote Bag",
            Price: 899,
            StockQuantity: 50,
            Description: "Elegant leather tote bag perfect for work and play.",
            ImageURLs: [
              "women-bag9-Women'sLeatherToteBag1",
              "women-bag9-Women'sLeatherToteBag2",
              "women-bag9-Women'sLeatherToteBag3",
              "women-bag9-Women'sLeatherToteBag4",
            ],
            SKU: "WLTB-001",
            IsActive: true,
            ProductType: "Tote Bag",
            Brand: "Brand I",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Canvas Crossbody Bag",
            Price: 599,
            StockQuantity: 100,
            Description: "Casual canvas crossbody bag for everyday use.",
            ImageURLs: [
              "women-bag10-Women'sCanvasCrossbodyBag1",
              "women-bag10-Women'sCanvasCrossbodyBag2",
              "women-bag10-Women'sCanvasCrossbodyBag3",
              "women-bag10-Women'sCanvasCrossbodyBag4",
            ],
            SKU: "WCCB-001",
            IsActive: true,
            ProductType: "Crossbody Bag",
            Brand: "Brand J",
            Color: "Olive",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Quilted Backpack",
            Price: 690,
            StockQuantity: 70,
            Description: "Stylish quilted backpack for a chic look.",
            ImageURLs: [
              "women-bag11-Women'sQuiltedBackpack1",
              "women-bag11-Women'sQuiltedBackpack2",
              "women-bag11-Women'sQuiltedBackpack3",
              "women-bag11-Women'sQuiltedBackpack4",
            ],
            SKU: "WQB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand K",
            Color: "Navy",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Mini Satchel Bag",
            Price: 1250,
            StockQuantity: 80,
            Description: "Cute mini satchel bag for a trendy look.",
            ImageURLs: [
              "women-bag12-Women'sMiniSatchelBag1",
              "women-bag12-Women'sMiniSatchelBag2",
              "women-bag12-Women'sMiniSatchelBag3",
              "women-bag12-Women'sMiniSatchelBag4",
            ],
            SKU: "WMSB-001",
            IsActive: true,
            ProductType: "Satchel Bag",
            Brand: "Brand L",
            Color: "Pink",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Faux Fur Clutch",
            Price: 1420,
            StockQuantity: 60,
            Description: "Chic faux fur clutch for evening events.",
            ImageURLs: [
              "women-bag13-Women'sFaux FurClutch1",
              "women-bag13-Women'sFaux FurClutch2",
              "women-bag13-Women'sFaux FurClutch3",
              "women-bag13-Women'sFaux FurClutch4",
            ],
            SKU: "WFFC-001",
            IsActive: true,
            ProductType: "Clutch Bag",
            Brand: "Brand M",
            Color: "White",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Sling Bag",
            Price: 499,
            StockQuantity: 90,
            Description: "Versatile sling bag for hands-free convenience.",
            ImageURLs: [
              "women-bag14-Women'sSlingBag1",
              "women-bag14-Women'sSlingBag2",
              "women-bag14-Women'sSlingBag3",
              "women-bag14-Women'sSlingBag4",
            ],
            SKU: "WSB-002",
            IsActive: true,
            ProductType: "Sling Bag",
            Brand: "Brand N",
            Color: "Red",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Travel Duffel Bag",
            Price: 799,
            StockQuantity: 40,
            Description: "Spacious duffel bag for weekend getaways.",
            ImageURLs: [
              "women-bag15-Women'sTravelDuffelBag1",
              "women-bag15-Women'sTravelDuffelBag2",
              "women-bag15-Women'sTravelDuffelBag3",
              "women-bag15-Women'sTravelDuffelBag4",
            ],
            SKU: "WTDB-001",
            IsActive: true,
            ProductType: "Duffel Bag",
            Brand: "Brand O",
            Color: "Gray",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Bucket Bag",
            Price: 799,
            StockQuantity: 30,
            Description: "Trendy bucket bag with drawstring closure.",
            ImageURLs: [
              "women-bag16-Women'sBucketBag1",
              "women-bag16-Women'sBucketBag2",
              "women-bag16-Women'sBucketBag3",
              "women-bag16-Women'sBucketBag4",
            ],
            SKU: "WBB-002",
            IsActive: true,
            ProductType: "Bucket Bag",
            Brand: "Brand P",
            Color: "Tan",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Watch",
        Description: "Women's watches including elegant and casual styles.",
        ImageURL: "women-watch",
        IsActive: true,
        categories: [
          {
            ProductName: "Women's Fashion Watch",
            Price: 799,
            StockQuantity: 50,
            Description: "Stylish fashion watch for women.",
            ImageURLs: [
              "women-watch1-Women'sFashionWatch1",
              "women-watch1-Women'sFashionWatch2",
              "women-watch1-Women'sFashionWatch3",
              "women-watch1-Women'sFashionWatch4",
            ],
            SKU: "WF-001",
            IsActive: true,
            ProductType: "Watch",
            Brand: "Brand A",
            Color: "Rose Gold",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Smart Watch",
            Price: 1299,
            StockQuantity: 30,
            Description: "Smart watch with fitness tracking features.",
            ImageURLs: [
              "women-watch2-Women'sSmartWatch1",
              "women-watch2-Women'sSmartWatch2",
              "women-watch2-Women'sSmartWatch3",
              "women-watch2-Women'sSmartWatch4",
            ],
            SKU: "WSW-001",
            IsActive: true,
            ProductType: "Smart Watch",
            Brand: "Brand B",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Classic Leather Watch",
            Price: 899,
            StockQuantity: 40,
            Description:
              "Elegant leather strap watch for a sophisticated look.",
            ImageURLs: [
              "women-watch3-Women'sClassicLeatherWatch1",
              "women-watch3-Women'sClassicLeatherWatch2",
              "women-watch3-Women'sClassicLeatherWatch3",
              "women-watch3-Women'sClassicLeatherWatch4",
            ],
            SKU: "WCLW-001",
            IsActive: true,
            ProductType: "Leather Watch",
            Brand: "Brand C",
            Color: "Brown",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Digital Watch",
            Price: 899,
            StockQuantity: 100,
            Description: "Digital watch with multiple features.",
            ImageURLs: [
              "women-watch4-Women'sDigitalWatch1",
              "women-watch4-Women'sDigitalWatch2",
              "women-watch4-Women'sDigitalWatch3",
              "women-watch4-Women'sDigitalWatch4",
            ],
            SKU: "WDW-001",
            IsActive: true,
            ProductType: "Digital Watch",
            Brand: "Brand D",
            Color: "Pink",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Crystal-Embellished Watch",
            Price: 1299,
            StockQuantity: 20,
            Description:
              "Luxury watch adorned with crystals for a glamorous look.",
            ImageURLs: [
              "women-watch5-Women'sCrystal-EmbellishedWatch1",
              "women-watch5-Women'sCrystal-EmbellishedWatch2",
              "women-watch5-Women'sCrystal-EmbellishedWatch3",
              "women-watch5-Women'sCrystal-EmbellishedWatch4",
            ],
            SKU: "WCW-001",
            IsActive: true,
            ProductType: "Fashion Watch",
            Brand: "Brand E",
            Color: "Silver",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Sport Watch",
            Price: 699,
            StockQuantity: 35,
            Description: "Durable sport watch designed for active lifestyles.",
            ImageURLs: [
              "women-watch6-Women'sSportWatch1",
              "women-watch6-Women'sSportWatch2",
              "women-watch6-Women'sSportWatch3",
              "women-watch6-Women'sSportWatch4",
            ],
            SKU: "WSW-002",
            IsActive: true,
            ProductType: "Sport Watch",
            Brand: "Brand F",
            Color: "Blue",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Vintage Style Watch",
            Price: 1399,
            StockQuantity: 60,
            Description: "Charming vintage style watch for a classic look.",
            ImageURLs: [
              "women-watch7-Women'sVintageStyleWatch1",
              "women-watch7-Women'sVintageStyleWatch2",
              "women-watch7-Women'sVintageStyleWatch3",
              "women-watch7-Women'sVintageStyleWatch4",
            ],
            SKU: "WVSW-001",
            IsActive: true,
            ProductType: "Vintage Watch",
            Brand: "Brand G",
            Color: "Gold",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Minimalist Watch",
            Price: 999,
            StockQuantity: 80,
            Description: "Sleek and minimalist watch for everyday wear.",
            ImageURLs: [
              "women-watch8-Women'sMinimalistWatch1",
              "women-watch8-Women'sMinimalistWatch2",
              "women-watch8-Women'sMinimalistWatch3",
              "women-watch8-Women'sMinimalistWatch4",
            ],
            SKU: "WMW-001",
            IsActive: true,
            ProductType: "Minimalist Watch",
            Brand: "Brand H",
            Color: "White",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Elegant Dress Watch",
            Price: 799,
            StockQuantity: 45,
            Description: "A sophisticated dress watch with a sleek design.",
            ImageURLs: [
              "women-watch9-Women'sElegantDressWatch1",
              "women-watch9-Women'sElegantDressWatch2",
              "women-watch9-Women'sElegantDressWatch3",
              "women-watch9-Women'sElegantDressWatch4",
            ],
            SKU: "WEDW-001",
            IsActive: true,
            ProductType: "Dress Watch",
            Brand: "Brand I",
            Color: "Silver",
            Size: "N/A",
            Featured: true,
          },

          {
            ProductName: "Women's Rose Gold Mesh Watch",
            Price: 790,
            StockQuantity: 60,
            Description: "Stylish rose gold mesh watch for a modern look.",
            ImageURLs: [
              "women-watch10-Women'sRoseGoldMeshWatch1",
              "women-watch10-Women'sRoseGoldMeshWatch2",
              "women-watch10-Women'sRoseGoldMeshWatch3",
              "women-watch10-Women'sRoseGoldMeshWatch4",
            ],
            SKU: "WRGMW-001",
            IsActive: true,
            ProductType: "Mesh Watch",
            Brand: "Brand K",
            Color: "Rose Gold",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Casual Silicone Watch",
            Price: 1430,
            StockQuantity: 100,
            Description: "Colorful silicone watch perfect for casual outings.",
            ImageURLs: [
              "women-watch11-Women'sCasualSiliconeWatch1",
              "women-watch11-Women'sCasualSiliconeWatch2",
              "women-watch11-Women'sCasualSiliconeWatch3",
              "women-watch11-Women'sCasualSiliconeWatch4",
            ],
            SKU: "WCSW-001",
            IsActive: true,
            ProductType: "Silicone Watch",
            Brand: "Brand L",
            Color: "Pink",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Luxury Diamond Watch",
            Price: 1542,
            StockQuantity: 15,
            Description:
              "Luxury watch adorned with diamonds for a glamorous touch.",
            ImageURLs: [
              "women-watch12-Women'sLuxuryDiamondWatch1",
              "women-watch12-Women'sLuxuryDiamondWatch2",
              "women-watch12-Women'sLuxuryDiamondWatch3",
              "women-watch12-Women'sLuxuryDiamondWatch4",
            ],
            SKU: "WLDW-001",
            IsActive: true,
            ProductType: "Luxury Watch",
            Brand: "Brand M",
            Color: "Gold",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Sporty Chronograph Watch",
            Price: 980,
            StockQuantity: 30,
            Description:
              "Durable chronograph watch designed for sports enthusiasts.",
            ImageURLs: [
              "women-watch13-Women'sSportyChronographWatch1",
              "women-watch13-Women'sSportyChronographWatch2",
              "women-watch13-Women'sSportyChronographWatch3",
              "women-watch13-Women'sSportyChronographWatch4",
            ],
            SKU: "WSCW-001",
            IsActive: true,
            ProductType: "Chronograph Watch",
            Brand: "Brand N",
            Color: "Blue",
            Size: "N/A",
            Featured: false,
          },

          {
            ProductName: "Women's Minimalist Analog Watch",
            Price: 960,
            StockQuantity: 80,
            Description: "Sleek minimalist analog watch for everyday elegance.",
            ImageURLs: [
              "women-watch14-Women'sMinimalistAnalogWatch1",
              "women-watch14-Women'sMinimalistAnalogWatch2",
              "women-watch14-Women'sMinimalistAnalogWatch3",
              "women-watch14-Women'sMinimalistAnalogWatch4",
            ],
            SKU: "WMAW-001",
            IsActive: true,
            ProductType: "Analog Watch",
            Brand: "Brand P",
            Color: "White",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Perfume",
        Description: "Women's perfumes and fragrances.",
        ImageURL: "women-perfume",
        IsActive: true,
        categories: [
          {
            ProductName: "Women's Eau de Parfum",
            Price: 599,
            StockQuantity: 40,
            Description: "Elegant eau de parfum for special occasions.",
            ImageURLs: [
              "women-perfume1-Women'sEaudeParfum1",
              "women-perfume1-Women'sEaudeParfum2",
              "women-perfume1-Women'sEaudeParfum3",
              "women-perfume1-Women'sEaudeParfum4",
            ],
            SKU: "WEP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand A",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },

          {
            ProductName: "Women's Sweet Vanilla Perfume",
            Price: 399,
            StockQuantity: 50,
            Description: "Warm and sweet vanilla scent for a cozy feel.",
            ImageURLs: [
              "women-perfume2-Women'sSweetVanillaPerfume1",
              "women-perfume2-Women'sSweetVanillaPerfume2",
              "women-perfume2-Women'sSweetVanillaPerfume3",
              "women-perfume2-Women'sSweetVanillaPerfume4",
            ],
            SKU: "WSVP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand C",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },

          {
            ProductName: "Women's Exotic Jasmine Perfume",
            Price: 690,
            StockQuantity: 20,
            Description: "Rich jasmine fragrance for a luxurious touch.",
            ImageURLs: [
              "women-perfume3-Women'sExoticJasminePerfume1",
              "women-perfume3-Women'sExoticJasminePerfume2",
              "women-perfume3-Women'sExoticJasminePerfume3",
              "women-perfume3-Women'sExoticJasminePerfume4",
            ],
            SKU: "WEJP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand E",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },
          {
            ProductName: "Women's Romantic Rose Perfume",
            Price: 745,
            StockQuantity: 25,
            Description: "Classic rose fragrance for a romantic feel.",
            ImageURLs: [
              "women-perfume4-Women'sRomanticRosePerfume1",
              "women-perfume4-Women'sRomanticRosePerfume2",
              "women-perfume4-Women'sRomanticRosePerfume3",
              "women-perfume4-Women'sRomanticRosePerfume4",
            ],
            SKU: "WRRP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand F",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },

          {
            ProductName: "Women Dusk Eau De Parfum",
            Price: 863,
            StockQuantity: 15,
            Description: "Intense fragrance for evening wear.",
            ImageURLs: [
              "women-perfume5-WomenDuskEauDeParfum1",
              "women-perfume5-WomenDuskEauDeParfum2",
              "women-perfume5-WomenDuskEauDeParfum3",
              "women-perfume5-WomenDuskEauDeParfum4",
            ],
            SKU: "WNMP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand H",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },
          {
            ProductName: "Women's Signature Scent",
            Price: 775,
            StockQuantity: 50,
            Description:
              "A signature scent that embodies elegance and sophistication.",
            ImageURLs: [
              "women-perfume6-Women'sSignatureScent1",
              "women-perfume6-Women'sSignatureScent2",
              "women-perfume6-Women'sSignatureScent3",
              "women-perfume6-Women'sSignatureScent4",
            ],
            SKU: "WSS-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand I",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },

          {
            ProductName: "Women's Spicy Amber Perfume",
            Price: 869,
            StockQuantity: 30,
            Description:
              "A warm and spicy amber fragrance for a bold statement.",
            ImageURLs: [
              "women-perfume7-Women'sSpicyAmberPerfume1",
              "women-perfume7-Women'sSpicyAmberPerfume2",
              "women-perfume7-Women'sSpicyAmberPerfume3",
              "women-perfume7-Women'sSpicyAmberPerfume4",
            ],
            SKU: "WSAP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand K",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },
          {
            ProductName: "Women's Premium Edition Muse Eau De Parfum",
            Price: 580,
            StockQuantity: 60,
            Description:
              "A light and airy fragrance reminiscent of ocean breezes.",
            ImageURLs: [
              "women-perfume8-Women'sPremiumEditionMuseEauDeParfum1",
              "women-perfume8-Women'sPremiumEditionMuseEauDeParfum2",
              "women-perfume8-Women'sPremiumEditionMuseEauDeParfum3",
              "women-perfume8-Women'sPremiumEditionMuseEauDeParfum4",
            ],
            SKU: "WOMP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand L",
            Color: "N/A",
            Size: "100ml",
            Featured: false,
          },
          {
            ProductName: "Women's Midnight Orchid Perfume",
            Price: 935,
            StockQuantity: 20,
            Description: "An enchanting floral fragrance for evening wear.",
            ImageURLs: [
              "women-perfume9-Women'sMidnightOrchidPerfume1",
              "women-perfume9-Women'sMidnightOrchidPerfume2",
              "women-perfume9-Women'sMidnightOrchidPerfume3",
              "women-perfume9-Women'sMidnightOrchidPerfume4",
            ],
            SKU: "WMOP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand M",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },

          {
            ProductName: "Women's Elegant Peony Perfume",
            Price: 797,
            StockQuantity: 40,
            Description: "A delicate peony fragrance that exudes femininity.",
            ImageURLs: [
              "women-perfume10-Women'sElegantPeonyPerfume1",
              "women-perfume10-Women'sElegantPeonyPerfume2",
              "women-perfume10-Women'sElegantPeonyPerfume3",
              "women-perfume10-Women'sElegantPeonyPerfume4",
            ],
            SKU: "WEP-001",
            IsActive: true,
            ProductType: "Eau de Parfum",
            Brand: "Brand O",
            Color: "N/A",
            Size: "100ml",
            Featured: true,
          },
        ],
      },
      {
        SubcategoryName: "Sunglasses",
        Description: "Women's sunglasses for style and protection.",
        ImageURL: "women-sunglasses",
        IsActive: true,
        categories: [
          {
            ProductName: "Women's Cat Eye Sunglasses",
            Price: 340,
            StockQuantity: 150,
            Description: "Trendy cat eye sunglasses for a chic look.",
            ImageURLs: [
              "women-sunglasses1-Women'sCatEyeSunglasses1",
              "women-sunglasses1-Women'sCatEyeSunglasses2",
              "women-sunglasses1-Women'sCatEyeSunglasses3",
              "women-sunglasses1-Women'sCatEyeSunglasses4",
            ],
            SKU: "WCES-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand A",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Oversized Round Sunglasses",
            Price: 399,
            StockQuantity: 120,
            Description:
              "Fashionable oversized round sunglasses for a bold statement.",
            ImageURLs: [
              "women-sunglasses2-Women'sOversizedRoundSunglasses1",
              "women-sunglasses2-Women'sOversizedRoundSunglasses2",
              "women-sunglasses2-Women'sOversizedRoundSunglasses3",
              "women-sunglasses2-Women'sOversizedRoundSunglasses4",
            ],
            SKU: "WORS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand B",
            Color: "Tortoise",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Aviator Sunglasses",
            Price: 589,
            StockQuantity: 100,
            Description: "Classic aviator sunglasses for a timeless look.",
            ImageURLs: [
              "women-sunglasses3-Women'sAviatorSunglasses1",
              "women-sunglasses3-Women'sAviatorSunglasses2",
              "women-sunglasses3-Women'sAviatorSunglasses3",
              "women-sunglasses3-Women'sAviatorSunglasses4",
            ],
            SKU: "WAS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand C",
            Color: "Gold",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Mirrored Sunglasses",
            Price: 569,
            StockQuantity: 80,
            Description: "Trendy mirrored sunglasses for a stylish edge.",
            ImageURLs: [
              "women-sunglasses4-Women'sMirroredSunglasses1",
              "women-sunglasses4-Women'sMirroredSunglasses2",
              "women-sunglasses4-Women'sMirroredSunglasses3",
              "women-sunglasses4-Women'sMirroredSunglasses4",
            ],
            SKU: "WMS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand D",
            Color: "Silver",
            Size: "N/A",
            Featured: false,
          },

          {
            ProductName: "Women's Sport Sunglasses",
            Price: 889,
            StockQuantity: 40,
            Description:
              "Durable sport sunglasses designed for outdoor activities.",
            ImageURLs: [
              "women-sunglasses5-Women'sSportSunglasses1",
              "women-sunglasses5-Women'sSportSunglasses2",
              "women-sunglasses5-Women'sSportSunglasses3",
              "women-sunglasses5-Women'sSportSunglasses4",
            ],
            SKU: "WSS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand F",
            Color: "Blue",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Square Sunglasses",
            Price: 689,
            StockQuantity: 70,
            Description: "Stylish square sunglasses for a modern look.",
            ImageURLs: [
              "women-sunglasses6-Women'sSquareSunglasses1",
              "women-sunglasses6-Women'sSquareSunglasses2",
              "women-sunglasses6-Women'sSquareSunglasses3",
              "women-sunglasses6-Women'sSquareSunglasses4",
            ],
            SKU: "WQS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand G",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Gradient Lens Sunglasses",
            Price: 899,
            StockQuantity: 30,
            Description:
              "Chic sunglasses with gradient lenses for a fashionable touch.",
            ImageURLs: [
              "women-sunglasses7-Women'sGradientLensSunglasses1",
              "women-sunglasses7-Women'sGradientLensSunglasses2",
              "women-sunglasses7-Women'sGradientLensSunglasses3",
              "women-sunglasses7-Women'sGradientLensSunglasses4",
            ],
            SKU: "WGLS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand H",
            Color: "Pink",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Retro Cat Eye Sunglasses",
            Price: 578,
            StockQuantity: 150,
            Description: "Stylish retro cat eye sunglasses for a vintage look.",
            ImageURLs: [
              "women-sunglasses8-Women'sRetroCatEyeSunglasses1",
              "women-sunglasses8-Women'sRetroCatEyeSunglasses2",
              "women-sunglasses8-Women'sRetroCatEyeSunglasses3",
              "women-sunglasses8-Women'sRetroCatEyeSunglasses4",
            ],
            SKU: "WRCE-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand I",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Classic Wayfarer Sunglasses",
            Price: 885,
            StockQuantity: 120,
            Description: "Timeless wayfarer sunglasses for everyday wear.",
            ImageURLs: [
              "women-sunglasses9-Women'sClassicWayfarerSunglasses1",
              "women-sunglasses9-Women'sClassicWayfarerSunglasses2",
              "women-sunglasses9-Women'sClassicWayfarerSunglasses3",
              "women-sunglasses9-Women'sClassicWayfarerSunglasses4",
            ],
            SKU: "WW-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand J",
            Color: "Tortoise",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Oversized Square Sunglasses",
            Price: 950,
            StockQuantity: 100,
            Description:
              "Fashionable oversized square sunglasses for a bold statement.",
            ImageURLs: [
              "women-sunglasses10-Women'sOversizedSquareSunglasses1",
              "women-sunglasses10-Women'sOversizedSquareSunglasses2",
              "women-sunglasses10-Women'sOversizedSquareSunglasses3",
              "women-sunglasses10-Women'sOversizedSquareSunglasses4",
            ],
            SKU: "WOSS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand K",
            Color: "Gray",
            Size: "N/A",
            Featured: true,
          },

          {
            ProductName: "Women's Mirrored Aviator Sunglasses",
            Price: 779,
            StockQuantity: 60,
            Description:
              "Trendy mirrored aviator sunglasses for a stylish edge.",
            ImageURLs: [
              "women-sunglasses11-Women'sMirroredAviatorSunglasses1",
              "women-sunglasses11-Women'sMirroredAviatorSunglasses2",
              "women-sunglasses11-Women'sMirroredAviatorSunglasses3",
              "women-sunglasses11-Women'sMirroredAviatorSunglasses4",
            ],
            SKU: "WMAS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand M",
            Color: "Gold",
            Size: "N/A",
            Featured: true,
          },
        ],
      },
    ],
  },
  {
    CategoryName: "Children",
    Description: "Bags, Sunglasses, and Toys for children.",
    ImageURL: "children",
    IsActive: true,
    subcategories: [
      {
        SubcategoryName: "Bag",
        Description: "Children's bags including backpacks and lunch bags.",
        ImageURL: "children-bag",
        IsActive: true,
        categories: [
          {
            ProductName: "Children's Dinosaur Backpack",
            Price: 790,
            StockQuantity: 100,
            Description: "Fun dinosaur-themed backpack for school and play.",
            ImageURLs: [
              "children-bag1-Children'sDinosaurBackpack1",
              "children-bag1-Children'sDinosaurBackpack2",
              "children-bag1-Children'sDinosaurBackpack3",
              "children-bag1-Children'sDinosaurBackpack4",
            ],
            SKU: "CDB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand A",
            Color: "Green",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Unicorn Lunch Bag",
            Price: 859,
            StockQuantity: 150,
            Description: "Cute unicorn lunch bag to keep meals fresh.",
            ImageURLs: [
              "children-bag2-Children'sUnicornLunchBag1",
              "children-bag2-Children'sUnicornLunchBag2",
              "children-bag2-Children'sUnicornLunchBag3",
              "children-bag2-Children'sUnicornLunchBag4",
            ],
            SKU: "CULB-001",
            IsActive: true,
            ProductType: "Lunch Bag",
            Brand: "Brand B",
            Color: "Pink",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Children's Superhero Backpack",
            Price: 768,
            StockQuantity: 80,
            Description: "Stylish superhero backpack for little heroes.",
            ImageURLs: [
              "children-bag3-Children'sSuperheroBackpack1",
              "children-bag3-Children'sSuperheroBackpack2",
              "children-bag3-Children'sSuperheroBackpack3",
              "children-bag3-Children'sSuperheroBackpack4",
            ],
            SKU: "CSB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand C",
            Color: "Blue",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Princess Tote Bag",
            Price: 698,
            StockQuantity: 120,
            Description:
              "Lovely princess tote bag for carrying toys and books.",
            ImageURLs: [
              "children-bag4-Children'sPrincessToteBag1",
              "children-bag4-Children'sPrincessToteBag2",
              "children-bag4-Children'sPrincessToteBag3",
              "children-bag4-Children'sPrincessToteBag4",
            ],
            SKU: "CPTB-001",
            IsActive: true,
            ProductType: "Tote Bag",
            Brand: "Brand D",
            Color: "Purple",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Children's Animal Backpack",
            Price: 947,
            StockQuantity: 60,
            Description: "Adorable animal-shaped backpack for kids.",
            ImageURLs: [
              "children-bag5-Children'sAnimalBackpack1",
              "children-bag5-Children'sAnimalBackpack2",
              "children-bag5-Children'sAnimalBackpack3",
              "children-bag5-Children'sAnimalBackpack4",
            ],
            SKU: "CAB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand E",
            Color: "Yellow",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Sports Bag",
            Price: 854,
            StockQuantity: 40,
            Description: "Durable sports bag for carrying gear to practice.",
            ImageURLs: [
              "children-bag6-Children'sSportsBag1",
              "children-bag6-Children'sSportsBag2",
              "children-bag6-Children'sSportsBag3",
              "children-bag6-Children'sSportsBag4",
            ],
            SKU: "CSB-002",
            IsActive: true,
            ProductType: "Sports Bag",
            Brand: "Brand F",
            Color: "Red",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Children's Fairy Tale Backpack",
            Price: 965,
            StockQuantity: 70,
            Description: "Charming fairy tale-themed backpack for school.",
            ImageURLs: [
              "children-bag7-Children'sFairyTaleBackpack1",
              "children-bag7-Children'sFairyTaleBackpack2",
              "children-bag7-Children'sFairyTaleBackpack3",
              "children-bag7-Children'sFairyTaleBackpack4",
            ],
            SKU: "CFTB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand G",
            Color: "Light Blue",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Robot Backpack",
            Price: 765,
            StockQuantity: 80,
            Description: "Stylish robot-themed backpack for tech lovers.",
            ImageURLs: [
              "children-bag8-Children'sRobotBackpack1",
              "children-bag8-Children'sRobotBackpack2",
              "children-bag8-Children'sRobotBackpack3",
              "children-bag8-Children'sRobotBackpack4",
            ],
            SKU: "CRB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand K",
            Color: "Gray",
            Size: "N/A",
            Featured: true,
          },

          {
            ProductName: "Children's Adventure Backpack",
            Price: 965,
            StockQuantity: 60,
            Description: "Durable adventure backpack for outdoor activities.",
            ImageURLs: [
              "children-bag9-Children'sAdventureBackpack1",
              "children-bag9-Children'sAdventureBackpack2",
              "children-bag9-Children'sAdventureBackpack3",
              "children-bag9-Children'sAdventureBackpack4",
            ],
            SKU: "CAB-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand M",
            Color: "Green",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Sports Duffel Bag",
            Price: 658,
            StockQuantity: 50,
            Description: "Spacious duffel bag for sports gear and activities.",
            ImageURLs: [
              "children-bag10-Children'sSportsDuffelBag1",
              "children-bag10-Children'sSportsDuffelBag2",
              "children-bag10-Children'sSportsDuffelBag3",
              "children-bag10-Children'sSportsDuffelBag4",
            ],
            SKU: "CSD-001",
            IsActive: true,
            ProductType: "Duffel Bag",
            Brand: "Brand P",
            Color: "Red",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Sunglasses",
        Description: "Children's sunglasses for style and protection.",
        ImageURL: "children-sunglasses",
        IsActive: true,
        categories: [
          {
            ProductName: "Children's Dinosaur Sunglasses",
            Price: 256,
            StockQuantity: 150,
            Description:
              "Fun dinosaur-themed sunglasses for little adventurers.",
            ImageURLs: [
              "children-sunglasses1-Children'sDinosaurSunglasses1",
              "children-sunglasses1-Children'sDinosaurSunglasses2",
              "children-sunglasses1-Children'sDinosaurSunglasses3",
              "children-sunglasses1-Children'sDinosaurSunglasses4",
            ],
            SKU: "CDS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand A",
            Color: "Green",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Unicorn Sunglasses",
            Price: 368,
            StockQuantity: 120,
            Description: "Cute unicorn sunglasses with colorful frames.",
            ImageURLs: [
              "children-sunglasses2-Children'sUnicornSunglasses1",
              "children-sunglasses2-Children'sUnicornSunglasses2",
              "children-sunglasses2-Children'sUnicornSunglasses3",
              "children-sunglasses2-Children'sUnicornSunglasses4",
            ],
            SKU: "CUS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand B",
            Color: "Pink",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Children's Aviator Sunglasses",
            Price: 852,
            StockQuantity: 100,
            Description: "Classic aviator sunglasses for a stylish look.",
            ImageURLs: [
              "children-sunglasses3-Children'sAviatorSunglasses1",
              "children-sunglasses3-Children'sAviatorSunglasses2",
              "children-sunglasses3-Children'sAviatorSunglasses3",
              "children-sunglasses3-Children'sAviatorSunglasses4",
            ],
            SKU: "CAS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand C",
            Color: "Gold",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Cat Eye Sunglasses",
            Price: 685,
            StockQuantity: 80,
            Description: "Trendy cat eye sunglasses for fashionable kids.",
            ImageURLs: [
              "children-sunglasses4-Children'sCatEyeSunglasses1",
              "children-sunglasses4-Children'sCatEyeSunglasses2",
              "children-sunglasses4-Children'sCatEyeSunglasses3",
              "children-sunglasses4-Children'sCatEyeSunglasses4",
            ],
            SKU: "CCES-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand D",
            Color: "Purple",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Children's Polarized Sports Sunglasses",
            Price: 568,
            StockQuantity: 60,
            Description: "Durable polarized sunglasses for outdoor activities.",
            ImageURLs: [
              "children-sunglasses5-Children'sPolarizedSportsSunglasses1",
              "children-sunglasses5-Children'sPolarizedSportsSunglasses2",
              "children-sunglasses5-Children'sPolarizedSportsSunglasses3",
              "children-sunglasses5-Children'sPolarizedSportsSunglasses4",
            ],
            SKU: "CPS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand E",
            Color: "Blue",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Round Sunglasses",
            Price: 533,
            StockQuantity: 90,
            Description: "Classic round sunglasses for a retro vibe.",
            ImageURLs: [
              "children-sunglasses6-Children'sRoundSunglasses1",
              "children-sunglasses6-Children'sRoundSunglasses2",
              "children-sunglasses6-Children'sRoundSunglasses3",
              "children-sunglasses6-Children'sRoundSunglasses4",
            ],
            SKU: "CRS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand F",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Children's Butterfly Sunglasses",
            Price: 452,
            StockQuantity: 50,
            Description:
              "Adorable butterfly-shaped sunglasses for little ones.",
            ImageURLs: [
              "children-sunglasses7-Children'sButterflySunglasses1",
              "children-sunglasses7-Children'sButterflySunglasses2",
              "children-sunglasses7-Children'sButterflySunglasses3",
              "children-sunglasses7-Children'sButterflySunglasses4",
            ],
            SKU: "CBS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand H",
            Color: "Pink",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Children's Shark Sunglasses",
            Price: 856,
            StockQuantity: 140,
            Description:
              "Fun shark-themed sunglasses for little ocean explorers.",
            ImageURLs: [
              "children-sunglasses8-Children'sSharkSunglasses1",
              "children-sunglasses8-Children'sSharkSunglasses2",
              "children-sunglasses8-Children'sSharkSunglasses3",
              "children-sunglasses8-Children'sSharkSunglasses4",
            ],
            SKU: "CSS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand I",
            Color: "Blue",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Superhero Sunglasses",
            Price: 569,
            StockQuantity: 70,
            Description:
              "Heroic sunglasses for little superheroes in training.",
            ImageURLs: [
              "children-sunglasses9-Children'sSuperheroSunglasses1",
              "children-sunglasses9-Children'sSuperheroSunglasses2",
              "children-sunglasses9-Children'sSuperheroSunglasses3",
              "children-sunglasses9-Children'sSuperheroSunglasses4",
            ],
            SKU: "CSS-003",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand M",
            Color: "Red",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Children's Cute Bear Sunglasses",
            Price: 523,
            StockQuantity: 150,
            Description: "Adorable bear-shaped sunglasses for playful kids.",
            ImageURLs: [
              "children-sunglasses10-Children'sCuteBearSunglasses1",
              "children-sunglasses10-Children'sCuteBearSunglasses2",
              "children-sunglasses10-Children'sCuteBearSunglasses3",
              "children-sunglasses10-Children'sCuteBearSunglasses4",
            ],
            SKU: "CBS-002",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand N",
            Color: "Brown",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Children's Glitter Sunglasses",
            Price: 325,
            StockQuantity: 80,
            Description: "Sparkly glitter sunglasses for a touch of glam.",
            ImageURLs: [
              "children-sunglasses11-Children'sGlitterSunglasses1",
              "children-sunglasses11-Children'sGlitterSunglasses2",
              "children-sunglasses11-Children'sGlitterSunglasses3",
              "children-sunglasses11-Children'sGlitterSunglasses4",
            ],
            SKU: "CGS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand O",
            Color: "Gold",
            Size: "N/A",
            Featured: true,
          },
        ],
      },
      {
        SubcategoryName: "Toys",
        Description: "Toys for children of all ages.",
        ImageURL: "children-toy",
        IsActive: true,
        categories: [
          {
            ProductName: "Building Blocks Set",
            Price: 399,
            StockQuantity: 200,
            Description: "A fun building blocks set for creative play.",
            ImageURLs: [
              "children-toy1-BuildingBlocksSet1",
              "children-toy1-BuildingBlocksSet2",
              "children-toy1-BuildingBlocksSet3",
              "children-toy1-BuildingBlocksSet4",
            ],
            SKU: "BBS-002",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand A",
            Color: "Multicolor",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Wooden Building Blocks",
            Price: 256,
            StockQuantity: 150,
            Description:
              "Colorful wooden blocks for creative building and play.",
            ImageURLs: [
              "children-toy2-WoodenBuildingBlocks1",
              "children-toy2-WoodenBuildingBlocks2",
              "children-toy2-WoodenBuildingBlocks3",
              "children-toy2-WoodenBuildingBlocks4",
            ],
            SKU: "WBB-001",
            IsActive: true,
            ProductType: "Building Toy",
            Brand: "Brand A",
            Color: "Multi",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Plush Teddy Bear",
            Price: 750,
            StockQuantity: 200,
            Description:
              "Soft and cuddly teddy bear for hugs and companionship.",
            ImageURLs: [
              "children-toy3-PlushTeddyBear1",
              "children-toy3-PlushTeddyBear2",
              "children-toy3-PlushTeddyBear3",
              "children-toy3-PlushTeddyBear4",
            ],
            SKU: "PTB-001",
            IsActive: true,
            ProductType: "Stuffed Animal",
            Brand: "Brand B",
            Color: "Brown",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Toy Kitchen Set",

            Price: 420,
            StockQuantity: 100,
            Description: "A complete kitchen set for pretend play.",
            ImageURLs: [
              "children-toy4-ToyKitchenSet1",
              "children-toy4-ToyKitchenSet2",
              "children-toy4-ToyKitchenSet3",
              "children-toy4-ToyKitchenSet4",
            ],
            SKU: "TKS-001",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand B",
            Color: "Pink",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Stuffed Dall Toy",

            Price: 630,
            StockQuantity: 150,
            Description: "A soft and cuddly stuffed animal.",
            ImageURLs: [
              "children-toy5-StuffedDallToy1",
              "children-toy5-StuffedDallToy2",
              "children-toy5-StuffedDallToy3",
              "children-toy5-StuffedDallToy4",
            ],
            SKU: "SAT-002",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand C",
            Color: "Brown",
            Size: "Medium",
            Featured: true,
          },
          {
            ProductName: "Toy Car Set",

            Price: 560,
            StockQuantity: 100,
            Description: "A set of toy cars for kids.",
            ImageURLs: [
              "children-toy6-ToyCarSet1",
              "children-toy6-ToyCarSet2",
              "children-toy6-ToyCarSet3",
              "children-toy6-ToyCarSet4",
            ],
            SKU: "TCS-002",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand D",
            Color: "Red",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Puzzle Game",

            Price: 420,
            StockQuantity: 120,
            Description: "A fun and educational puzzle game for kids.",
            ImageURLs: [
              "children-toy7-PuzzleGame1",
              "children-toy7-PuzzleGame2",
              "children-toy7-PuzzleGame3",
              "children-toy7-PuzzleGame4",
            ],
            SKU: "PG-001",
            IsActive: true,
            ProductType: "Puzzle",
            Brand: "Brand E",
            Color: "Multicolor",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Action Figure Set",

            Price: 630,
            StockQuantity: 80,
            Description: "A set of action figures for imaginative play.",
            ImageURLs: [
              "children-toy8-ActionFigureSet1",
              "children-toy8-ActionFigureSet2",
              "children-toy8-ActionFigureSet3",
              "children-toy8-ActionFigureSet4",
            ],
            SKU: "AFS-001",
            IsActive: true,
            ProductType: "Action Figure",
            Brand: "Brand F",
            Color: "Various",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Remote Control Car",
            Price: 753,
            StockQuantity: 40,
            Description: "Fast and fun remote control car for outdoor racing.",
            ImageURLs: [
              "children-toy9-RemoteControlCar1",
              "children-toy9-RemoteControlCar2",
              "children-toy9-RemoteControlCar3",
              "children-toy9-RemoteControlCar4",
            ],
            SKU: "RCC-001",
            IsActive: true,
            ProductType: "Vehicle",
            Brand: "Brand G",
            Color: "Red",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Musical Instruments Set",
            Price: 590,
            StockQuantity: 50,
            Description: "Colorful musical instruments for little musicians.",
            ImageURLs: [
              "children-toy10-MusicalInstrumentsSet1",
              "children-toy10-MusicalInstrumentsSet2",
              "children-toy10-MusicalInstrumentsSet3",
              "children-toy10-MusicalInstrumentsSet4",
            ],
            SKU: "MIS-001",
            IsActive: true,
            ProductType: "Musical Toy",
            Brand: "Brand H",
            Color: "Multi",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
    ],
  },
];

async function seedDatabase() {
  try {
    // Clear existing data
    await Category.deleteMany({});
    await Subcategory.deleteMany({});
    await Product.deleteMany({});

    // Loop through each category
    for (const categoryData of data) {
      const category = new Category({
        CategoryName: categoryData.CategoryName,
        Description: categoryData.Description,
        ImageURL: categoryData.ImageURL,
        IsActive: categoryData.IsActive,
      });

      // Save the category
      const savedCategory = await category.save();

      // Loop through each subcategory
      for (const subcategoryData of categoryData.subcategories) {
        const subcategory = new Subcategory({
          SubcategoryName: subcategoryData.SubcategoryName,
          CategoryID: savedCategory._id,
          Description: subcategoryData.Description,
          ImageURL: subcategoryData.ImageURL,
          IsActive: subcategoryData.IsActive,
        });

        // Save the subcategory
        const savedSubcategory = await subcategory.save();

        let i = 0;
        // Loop through each product
        for (const productData of subcategoryData.categories) {
          const product = new Product({
            ProductName: productData.ProductName,
            SubcategoryID: savedSubcategory._id,
            CategoryID: savedCategory._id,
            Price: productData.Price,
            StockQuantity: productData.StockQuantity,
            Description: productData.Description,
            ImageURLs: productData.ImageURLs,
            SKU: productData.SKU + i,
            IsActive: productData.IsActive,
            ProductType: productData.ProductType,
            Brand: productData.Brand,
            Color: productData.Color,
            Size: productData.Size,
            Featured: productData.Featured,
          });
          i++;

          // Save the product
          await product.save();
        }
      }
    }

    console.log("Database seeded successfully");
    mongoose.connection.close();
  } catch (error) {
    console.error("Error seeding database:", error);
  }
}
