const mongoose = require("mongoose");
const { ObjectId } = mongoose.Types; // Import ObjectId correctly
const Product = require("../models/Product"); // Adjust the path accordingly
const Subcategory = require("../models/Subcategory"); // Adjust the path accordingly

// Connect to MongoDB
mongoose
  .connect("mongodb://localhost:27017/shopping-kart", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log("MongoDB connected");
  })
  .catch((err) => {
    console.error("MongoDB connection error:", err);
  });

// Expanded dummy products data based on subcategories
const products = [
  // Men's Clothing Products
  {
    ProductName: "Men's Dress Shirt",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"), // Replace with actual SubcategoryID
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 39.99,
    StockQuantity: 90,
    Description: "Formal dress shirt for business and events.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MDS-001",
    IsActive: true,
    ProductType: "Shirt",
    Brand: "Brand A",
    Color: "White",
    Size: "L",
    Featured: true,
  },
  {
    ProductName: "Men's Cargo Pants",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 49.99,
    StockQuantity: 70,
    Description: "Comfortable cargo pants with multiple pockets.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MCP-001",
    IsActive: true,
    ProductType: "Pants",
    Brand: "Brand B",
    Color: "Olive",
    Size: "M",
    Featured: false,
  },
  {
    ProductName: "Men's Sports Jacket",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 89.99,
    StockQuantity: 40,
    Description: "Stylish sports jacket for casual outings.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MSJ-001",
    IsActive: true,
    ProductType: "Jacket",
    Brand: "Brand C",
    Color: "Navy",
    Size: "L",
    Featured: true,
  },
  {
    ProductName: "Men's Casual Shirt",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"), // Replace with actual SubcategoryID
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 29.99,
    StockQuantity: 100,
    Description: "A comfortable casual shirt for men.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MCS-001",
    IsActive: true,
    ProductType: "Shirt",
    Brand: "Brand A",
    Color: "Blue",
    Size: "M",
    Featured: false,
  },
  {
    ProductName: "Men's Formal Pants",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 49.99,
    StockQuantity: 80,
    Description: "Stylish formal pants for office wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MFP-001",
    IsActive: true,
    ProductType: "Pants",
    Brand: "Brand B",
    Color: "Black",
    Size: "L",
    Featured: true,
  },
  {
    ProductName: "Men's Denim Jacket",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 59.99,
    StockQuantity: 50,
    Description: "Classic denim jacket for men.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MDJ-001",
    IsActive: true,
    ProductType: "Jacket",
    Brand: "Brand C",
    Color: "Dark Blue",
    Size: "M",
    Featured: false,
  },
  {
    ProductName: "Men's Sports Shorts",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 24.99,
    StockQuantity: 150,
    Description: "Comfortable sports shorts for men.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MSS-001",
    IsActive: true,
    ProductType: "Shorts",
    Brand: "Brand D",
    Color: "Gray",
    Size: "L",
    Featured: true,
  },
  {
    ProductName: "Men's Polo Shirt",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 34.99,
    StockQuantity: 120,
    Description: "Stylish polo shirt for casual outings.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MPS-001",
    IsActive: true,
    ProductType: "Shirt",
    Brand: "Brand K",
    Color: "Green",
    Size: "L",
    Featured: true,
  },
  {
    ProductName: "Men's Chinos",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 49.99,
    StockQuantity: 60,
    Description: "Comfortable chinos for everyday wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MC-001",
    IsActive: true,
    ProductType: "Pants",
    Brand: "Brand L",
    Color: "Beige",
    Size: "M",
    Featured: false,
  },
  {
    ProductName: "Men's Hoodie",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faa"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 39.99,
    StockQuantity: 80,
    Description: "Cozy hoodie for chilly days.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MH-001",
    IsActive: true,
    ProductType: "Hoodie",
    Brand: "Brand M",
    Color: "Black",
    Size: "L",
    Featured: true,
  },
  // Men's Shoes Products
  {
    ProductName: "Men's Oxford Shoes",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"), // Replace with actual SubcategoryID
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 89.99,
    StockQuantity: 50,
    Description: "Classic Oxford shoes for formal occasions.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MOS-001",
    IsActive: true,
    ProductType: "Dress Shoes",
    Brand: "Brand A",
    Color: "Black",
    Size: "10",
    Featured: true,
  },
  {
    ProductName: "Men's Casual Loafers",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 59.99,
    StockQuantity: 70,
    Description: "Comfortable loafers for everyday wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MCL-001",
    IsActive: true,
    ProductType: "Loafers",
    Brand: "Brand B",
    Color: "Brown",
    Size: "11",
    Featured: false,
  },
  {
    ProductName: "Men's High-Top Sneakers",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 69.99,
    StockQuantity: 40,
    Description: "Stylish high-top sneakers for a trendy look.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MHTS-001",
    IsActive: true,
    ProductType: "Sneakers",
    Brand: "Brand C",
    Color: "Gray",
    Size: "9",
    Featured: true,
  },
  {
    ProductName: "Men's Slip-On Sneakers",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 49.99,
    StockQuantity: 60,
    Description: "Easy-to-wear slip-on sneakers for casual outings.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MSOS-001",
    IsActive: true,
    ProductType: "Sneakers",
    Brand: "Brand D",
    Color: "Navy",
    Size: "10",
    Featured: false,
  },
  {
    ProductName: "Men's Chelsea Boots",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 79.99,
    StockQuantity: 35,
    Description: "Classic Chelsea boots for a sophisticated look.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MCB-001",
    IsActive: true,
    ProductType: "Boots",
    Brand: "Brand D",
    Color: "Black",
    Size: "10",
    Featured: false,
  },
  {
    ProductName: "Men's Flip Flops",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 19.99,
    StockQuantity: 150,
    Description: "Comfortable flip flops for summer.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MFF-001",
    IsActive: true,
    ProductType: "Flip Flops",
    Brand: "Brand E",
    Color: "Blue",
    Size: "11",
    Featured: true,
  },
  {
    ProductName: "Men's Loafers",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 69.99,
    StockQuantity: 40,
    Description: "Elegant loafers for formal occasions.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "ML-001",
    IsActive: true,
    ProductType: "Loafers",
    Brand: "Brand N",
    Color: "Navy",
    Size: "10",
    Featured: false,
  },
  {
    ProductName: "Men's Hiking Boots",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 99.99,
    StockQuantity: 25,
    Description: "Durable hiking boots for outdoor adventures.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MHB-001",
    IsActive: true,
    ProductType: "Boots",
    Brand: "Brand O",
    Color: "Gray",
    Size: "11",
    Featured: true,
  },
  {
    ProductName: "Men's Running Shoes",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 59.99,
    StockQuantity: 50,
    Description: "Lightweight running shoes for men.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MRS-001",
    IsActive: true,
    ProductType: "Shoes",
    Brand: "Brand E",
    Color: "Black",
    Size: "10",
    Featured: true,
  },
  {
    ProductName: "Men's Leather Boots",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 89.99,
    StockQuantity: 30,
    Description: "Durable leather boots for men.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MLB-001",
    IsActive: true,
    ProductType: "Boots",
    Brand: "Brand F",
    Color: "Brown",
    Size: "11",
    Featured: false,
  },
  {
    ProductName: "Men's Casual Sneakers",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fab"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 49.99,
    StockQuantity: 70,
    Description: "Stylish casual sneakers for everyday wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MCS-002",
    IsActive: true,
    ProductType: "Sneakers",
    Brand: "Brand G",
    Color: "White",
    Size: "9",
    Featured: true,
  },

  // Men's Accessories Products
  {
    ProductName: "Men's Messenger Bag",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 49.99,
    StockQuantity: 60,
    Description: "Stylish messenger bag for work and travel.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MMB-001",
    IsActive: true,
    ProductType: "Messenger Bag",
    Brand: "Brand F",
    Color: "Brown",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Men's Scarf",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 24.99,
    StockQuantity: 100,
    Description: "Warm scarf for winter.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MS-002",
    IsActive: true,
    ProductType: "Scarf",
    Brand: "Brand G",
    Color: "Black",
    Size: "N/A",
    Featured: true,
  },
  {
    ProductName: "Men's Beanie Hat",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 19.99,
    StockQuantity: 120,
    Description: "Warm beanie hat for cold weather.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MBH-001",
    IsActive: true,
    ProductType: "Beanie",
    Brand: "Brand H",
    Color: "Dark Gray",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Men's Belt",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 24.99,
    StockQuantity: 200,
    Description: "Classic leather belt for men.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MB-001",
    IsActive: true,
    ProductType: "Belt",
    Brand: "Brand P",
    Color: "Black",
    Size: "M",
    Featured: false,
  },
  {
    ProductName: "Men's Backpack",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 59.99,
    StockQuantity: 50,
    Description: "Stylish and functional backpack for daily use.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MBK-001",
    IsActive: true,
    ProductType: "Backpack",
    Brand: "Brand Q",
    Color: "Black",
    Size: "N/A",
    Featured: true,
  },
  {
    ProductName: "Men's Beanie",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 19.99,
    StockQuantity: 150,
    Description: "Warm beanie for winter.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MB-002",
    IsActive: true,
    ProductType: "Beanie",
    Brand: "Brand R",
    Color: "Gray",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Men's Cufflinks",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 29.99,
    StockQuantity: 100,
    Description: "Elegant cufflinks for formal wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MC-002",
    IsActive: true,
    ProductType: "Cufflinks",
    Brand: "Brand S",
    Color: "Silver",
    Size: "N/A",
    Featured: true,
  },
  {
    ProductName: "Men's Tie",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 19.99,
    StockQuantity: 200,
    Description: "Classic tie for formal occasions.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MT-001",
    IsActive: true,
    ProductType: "Tie",
    Brand: "Brand T",
    Color: "Navy",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Men's Leather Wallet",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 39.99,
    StockQuantity: 150,
    Description: "A stylish leather wallet for men.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MLW-001",
    IsActive: true,
    ProductType: "Wallet",
    Brand: "Brand H",
    Color: "Black",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Men's Wrist Watch",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 199.99,
    StockQuantity: 20,
    Description: "Elegant wrist watch for men.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MW-001",
    IsActive: true,
    ProductType: "Watch",
    Brand: "Brand I",
    Color: "Silver",
    Size: "N/A",
    Featured: true,
  },
  {
    ProductName: "Men's Sunglasses",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fac"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6a"),
    Price: 29.99,
    StockQuantity: 200,
    Description: "Stylish sunglasses for men.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "MS-001",
    IsActive: true,
    ProductType: "Sunglasses",
    Brand: "Brand J",
    Color: "Black",
    Size: "N/A",
    Featured: false,
  },

  // Women's Clothing Products
  {
    ProductName: "Women's Blazer",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"), // Replace with actual SubcategoryID
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 79.99,
    StockQuantity: 50,
    Description: "Stylish blazer for a professional look.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WBZ-001",
    IsActive: true,
    ProductType: "Blazer",
    Brand: "Brand A",
    Color: "Navy",
    Size: "M",
    Featured: true,
  },
  {
    ProductName: "Women's Maxi Skirt",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 39.99,
    StockQuantity: 80,
    Description: "Flowy maxi skirt for summer outings.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WMS-001",
    IsActive: true,
    ProductType: "Skirt",
    Brand: "Brand B",
    Color: "Floral",
    Size: "L",
    Featured: false,
  },
  {
    ProductName: "Women's Tunic Dress",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 49.99,
    StockQuantity: 60,
    Description: "Comfortable tunic dress for casual wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WTD-001",
    IsActive: true,
    ProductType: "Dress",
    Brand: "Brand C",
    Color: "Red",
    Size: "S",
    Featured: true,
  },
  {
    ProductName: "Women's Cardigan Sweater",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 44.99,
    StockQuantity: 70,
    Description: "Cozy cardigan sweater for layering.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WCS-001",
    IsActive: true,
    ProductType: "Sweater",
    Brand: "Brand D",
    Color: "Gray",
    Size: "M",
    Featured: false,
  },
  {
    ProductName: "Women's Activewear Leggings",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 29.99,
    StockQuantity: 100,
    Description: "Comfortable leggings for workouts.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WAL-001",
    IsActive: true,
    ProductType: "Leggings",
    Brand: "Brand E",
    Color: "Black",
    Size: "L",
    Featured: true,
  },
  {
    ProductName: "Women's Summer Shorts",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 24.99,
    StockQuantity: 90,
    Description: "Lightweight shorts for hot weather.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WSS-002",
    IsActive: true,
    ProductType: "Shorts",
    Brand: "Brand F",
    Color: "Beige",
    Size: "M",
    Featured: false,
  },
  {
    ProductName: "Women's Tunic Top",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"), // Replace with actual SubcategoryID
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 34.99,
    StockQuantity: 100,
    Description: "Stylish tunic top for casual wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WTT-001",
    IsActive: true,
    ProductType: "Tunic",
    Brand: "Brand A",
    Color: "Coral",
    Size: "M",
    Featured: true,
  },
  {
    ProductName: "Women's Pencil Skirt",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 49.99,
    StockQuantity: 80,
    Description: "Elegant pencil skirt for office wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WPS-001",
    IsActive: true,
    ProductType: "Skirt",
    Brand: "Brand B",
    Color: "Black",
    Size: "L",
    Featured: false,
  },
  {
    ProductName: "Women's Kimono Jacket",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 39.99,
    StockQuantity: 60,
    Description: "Lightweight kimono jacket for layering.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WKJ-001",
    IsActive: true,
    ProductType: "Jacket",
    Brand: "Brand C",
    Color: "Floral",
    Size: "S",
    Featured: true,
  },
  {
    ProductName: "Women's Cardigan",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 49.99,
    StockQuantity: 80,
    Description: "Cozy cardigan for layering.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WC-001",
    IsActive: true,
    ProductType: "Cardigan",
    Brand: "Brand U",
    Color: "Gray",
    Size: "L",
    Featured: false,
  },
  {
    ProductName: "Women's Jumpsuit",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 59.99,
    StockQuantity: 50,
    Description: "Stylish jumpsuit for a chic look.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WJ-001",
    IsActive: true,
    ProductType: "Jumpsuit",
    Brand: "Brand V",
    Color: "Black",
    Size: "S",
    Featured: true,
  },
  {
    ProductName: "Women's Summer Dress",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 49.99,
    StockQuantity: 75,
    Description: "A stylish summer dress for women.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WSD-001",
    IsActive: true,
    ProductType: "Dress",
    Brand: "Brand K",
    Color: "Red",
    Size: "L",
    Featured: false,
  },
  {
    ProductName: "Women's Maxi Dress",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fad"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 59.99,
    StockQuantity: 50,
    Description: "Flowy maxi dress for summer outings.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WMD-001",
    IsActive: true,
    ProductType: "Dress",
    Brand: "Brand M",
    Color: "Floral",
    Size: "S",
    Featured: false,
  },

  // Women's Shoes Products
  {
    ProductName: "Women's Ankle Strap Heels",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"), // Replace with actual SubcategoryID
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 69.99,
    StockQuantity: 40,
    Description: "Elegant ankle strap heels for formal occasions.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WASH-001",
    IsActive: true,
    ProductType: "Heels",
    Brand: "Brand A",
    Color: "Black",
    Size: "8",
    Featured: true,
  },
  {
    ProductName: "Women's Platform Sandals",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 49.99,
    StockQuantity: 60,
    Description: "Stylish platform sandals for summer.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WPS-002",
    IsActive: true,
    ProductType: "Sandals",
    Brand: "Brand B",
    Color: "Tan",
    Size: "7",
    Featured: false,
  },
  {
    ProductName: "Women's Ballerina Flats",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 39.99,
    StockQuantity: 80,
    Description: "Comfortable ballerina flats for everyday wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WBF-001",
    IsActive: true,
    ProductType: "Flats",
    Brand: "Brand C",
    Color: "Navy",
    Size: "8",
    Featured: true,
  },
  {
    ProductName: "Women's Combat Boots",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 89.99,
    StockQuantity: 30,
    Description: "Stylish combat boots for a rugged look.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WCB-002",
    IsActive: true,
    ProductType: "Boots",
    Brand: "Brand D",
    Color: "Black",
    Size: "9",
    Featured: false,
  },
  {
    ProductName: "Women's Slip-On Sneakers",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 44.99,
    StockQuantity: 50,
    Description: "Easy-to-wear slip-on sneakers for casual outings.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WSS-003",
    IsActive: true,
    ProductType: "Sneakers",
    Brand: "Brand E",
    Color: "White",
    Size: "8",
    Featured: true,
  },
  {
    ProductName: "Women's Hiking Shoes",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 99.99,
    StockQuantity: 25,
    Description: "Durable hiking shoes for outdoor adventures.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WHS-001",
    IsActive: true,
    ProductType: "Hiking Shoes",
    Brand: "Brand F",
    Color: "Gray",
    Size: "9",
    Featured: false,
  },
  {
    ProductName: "Women's Wedge Sandals",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 59.99,
    StockQuantity: 50,
    Description: "Stylish wedge sandals for summer outings.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WWS-001",
    IsActive: true,
    ProductType: "Wedge Sandals",
    Brand: "Brand D",
    Color: "Tan",
    Size: "8",
    Featured: false,
  },
  {
    ProductName: "Women's Slip-On Sneakers",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 49.99,
    StockQuantity: 70,
    Description: "Comfortable slip-on sneakers for everyday wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WSS-001",
    IsActive: true,
    ProductType: "Sneakers",
    Brand: "Brand E",
    Color: "White",
    Size: "7",
    Featured: true,
  },
  {
    ProductName: "Women's Sandals",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 39.99,
    StockQuantity: 60,
    Description: "Comfortable sandals for summer.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WS-002",
    IsActive: true,
    ProductType: "Sandals",
    Brand: "Brand W",
    Color: "Tan",
    Size: "8",
    Featured: false,
  },
  {
    ProductName: "Women's Combat Boots",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 89.99,
    StockQuantity: 30,
    Description: "Stylish combat boots for a rugged look.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WCB-001",
    IsActive: true,
    ProductType: "Boots",
    Brand: "Brand X",
    Color: "Black",
    Size: "9",
    Featured: true,
  },
  {
    ProductName: "Women's Heels",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 79.99,
    StockQuantity: 40,
    Description: "Stylish heels for women.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WH-001",
    IsActive: true,
    IsActive: true,
    ProductType: "Heels",
    Brand: "Brand N",
    Color: "Black",
    Size: "8",
    Featured: false,
  },
  {
    ProductName: "Women's Flats",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 39.99,
    StockQuantity: 60,
    Description: "Comfortable flats for everyday wear.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WF-001",
    IsActive: true,
    ProductType: "Flats",
    Brand: "Brand O",
    Color: "Navy",
    Size: "7",
    Featured: true,
  },
  {
    ProductName: "Women's Ankle Boots",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fae"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 89.99,
    StockQuantity: 30,
    Description: "Chic ankle boots for women.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WAB-001",
    IsActive: true,
    ProductType: "Boots",
    Brand: "Brand P",
    Color: "Brown",
    Size: "8",
    Featured: false,
  },

  // Women's Accessories Products

  {
    ProductName: "Women's Sunglasses",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faf"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 29.99,
    StockQuantity: 150,
    Description: "Stylish sunglasses for sunny days.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WSG-001",
    IsActive: true,
    ProductType: "Sunglasses",
    Brand: "Brand AA",
    Color: "Black",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Women's Watch",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faf"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 149.99,
    StockQuantity: 25,
    Description: "Elegant watch for women.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WW-001",
    IsActive: true,
    ProductType: "Watch",
    Brand: "Brand AB",
    Color: "Rose Gold",
    Size: "N/A",
    Featured: true,
  },
  {
    ProductName: "Women's Tote Bag",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faf"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 59.99,
    StockQuantity: 50,
    Description: "Stylish tote bag for everyday use.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WTB-001",
    IsActive: true,
    ProductType: "Tote Bag",
    Brand: "Brand Y",
    Color: "Beige",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Women's Hair Accessories Set",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faf"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 14.99,
    StockQuantity: 200,
    Description: "A set of stylish hair accessories.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WHA-001",
    IsActive: true,
    ProductType: "Hair Accessories",
    Brand: "Brand Z",
    Color: "Multicolor",
    Size: "N/A",
    Featured: true,
  },
  {
    ProductName: "Women's Handbag",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faf"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 89.99,
    StockQuantity: 50,
    Description: "Stylish handbag for women.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WHB-001",
    IsActive: true,
    ProductType: "Handbag",
    Brand: "Brand Q",
    Color: "Brown",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Women's Scarf",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faf"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 19.99,
    StockQuantity: 200,
    Description: "Fashionable scarf for women.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WS-001",
    IsActive: true,
    ProductType: "Scarf",
    Brand: "Brand R",
    Color: "Pink",
    Size: "N/A",
    Featured: true,
  },
  {
    ProductName: "Women's Jewelry Set",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916faf"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6b"),
    Price: 49.99,
    StockQuantity: 100,
    Description: "Elegant jewelry set for special occasions.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "WJS-001",
    IsActive: true,
    ProductType: "Jewelry",
    Brand: "Brand S",
    Color: "Gold",
    Size: "N/A",
    Featured: false,
  },

  // Children's Clothing Products
  {
    ProductName: "Children's Graphic T-Shirt",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"), // Replace with actual SubcategoryID
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 19.99,
    StockQuantity: 150,
    Description: "Fun graphic t-shirt for kids.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CGT-001",
    IsActive: true,
    ProductType: "T-Shirt",
    Brand: "Brand A",
    Color: "Blue",
    Size: "M",
    Featured: true,
  },
  {
    ProductName: "Children's Denim Jacket",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 49.99,
    StockQuantity: 80,
    Description: "Classic denim jacket for a stylish look.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CDJ-001",
    IsActive: true,
    ProductType: "Jacket",
    Brand: "Brand B",
    Color: "Light Blue",
    Size: "L",
    Featured: false,
  },
  {
    ProductName: "Children's Sweatpants",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 29.99,
    StockQuantity: 100,
    Description: "Comfortable sweatpants for playtime.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CSP-001",
    IsActive: true,
    ProductType: "Pants",
    Brand: "Brand C",
    Color: "Gray",
    Size: "S",
    Featured: true,
  },
  {
    ProductName: "Children's Summer Dress",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 34.99,
    StockQuantity: 70,
    Description: "Cute summer dress for girls.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CSD-001",
    IsActive: true,
    ProductType: "Dress",
    Brand: "Brand D",
    Color: "Pink",
    Size: "M",
    Featured: false,
  },
  {
    ProductName: "Children's Pajama Set",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 24.99,
    StockQuantity: 120,
    Description: "Cozy pajama set for a good night's sleep.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CPS-001",
    IsActive: true,
    ProductType: "Pajamas",
    Brand: "Brand E",
    Color: "Star Print",
    Size: "L",
    Featured: true,
  },
  {
    ProductName: "Children's Raincoat",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 39.99,
    StockQuantity: 50,
    Description: "Waterproof raincoat for rainy days.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CRC-001",
    IsActive: true,
    ProductType: "Raincoat",
    Brand: "Brand F",
    Color: "Yellow",
    Size: "S",
    Featured: false,
  },
  {
    ProductName: "Children's Hoodie",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"), // Replace with actual SubcategoryID
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 29.99,
    StockQuantity: 100,
    Description: "Cozy hoodie for kids.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CH-001",
    IsActive: true,
    ProductType: "Hoodie",
    Brand: "Brand A",
    Color: "Blue",
    Size: "M",
    Featured: true,
  },
  {
    ProductName: "Children's Overalls",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 39.99,
    StockQuantity: 80,
    Description: "Durable overalls for playtime.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CO-001",
    IsActive: true,
    ProductType: "Overalls",
    Brand: "Brand B",
    Color: "Denim",
    Size: "L",
    Featured: false,
  },
  {
    ProductName: "Children's Rain Jacket",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 34.99,
    StockQuantity: 60,
    Description: "Waterproof rain jacket for kids.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CRJ-001",
    IsActive: true,
    ProductType: "Jacket",
    Brand: "Brand C",
    Color: "Yellow",
    Size: "S",
    Featured: true,
  },
  {
    ProductName: "Children's T-Shirt",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 19.99,
    StockQuantity: 150,
    Description: "Comfortable t-shirt for kids.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CTS-001",
    IsActive: true,
    ProductType: "T-Shirt",
    Brand: "Brand T",
    Color: "Green",
    Size: "S",
    Featured: false,
  },
  {
    ProductName: "Children's Jacket",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 39.99,
    StockQuantity: 80,
    Description: "Warm jacket for children.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CJ-001",
    IsActive: true,
    ProductType: "Jacket",
    Brand: "Brand U",
    Color: "Red",
    Size: "M",
    Featured: true,
  },
  {
    ProductName: "Children's Dress",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb0"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 29.99,
    StockQuantity: 100,
    Description: "Cute dress for little girls.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CD-001",
    IsActive: true,
    ProductType: "Dress",
    Brand: "Brand V",
    Color: "Pink",
    Size: "L",
    Featured: false,
  },

  // Children's Shoes Products
  {
    ProductName: "Children's Rain Boots",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb1"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 34.99,
    StockQuantity: 60,
    Description: "Waterproof rain boots for wet weather.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CRB-001",
    IsActive: true,
    ProductType: "Rain Boots",
    Brand: "Brand C",
    Color: "Yellow",
    Size: "11",
    Featured: true,
  },
  {
    ProductName: "Children's Slip-On Shoes",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb1"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 29.99,
    StockQuantity: 70,
    Description: "Easy-to-wear slip-on shoes for everyday use.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CSOS-001",
    IsActive: true,
    ProductType: "Slip-On Shoes",
    Brand: "Brand E",
    Color: "Red",
    Size: "9",
    Featured: true,
  },
  {
    ProductName: "Children's Hiking Shoes",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb1"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 59.99,
    StockQuantity: 30,
    Description: "Durable hiking shoes for outdoor adventures.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CHS-001",
    IsActive: true,
    ProductType: "Hiking Shoes",
    Brand: "Brand F",
    Color: "Green",
    Size: "10",
    Featured: false,
  },
  {
    ProductName: "Children's Dress Shoes",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb1"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 49.99,
    StockQuantity: 40,
    Description: "Elegant dress shoes for special occasions.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CDS-001",
    IsActive: true,
    ProductType: "Dress Shoes",
    Brand: "Brand D",
    Color: "Black",
    Size: "10",
    Featured: false,
  },
  {
    ProductName: "Children's Waterproof Boots",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb1"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 59.99,
    StockQuantity: 30,
    Description: "Durable waterproof boots for outdoor play.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CWB-001",
    IsActive: true,
    ProductType: "Boots",
    Brand: "Brand E",
    Color: "Brown",
    Size: "11",
    Featured: true,
  },
  {
    ProductName: "Children's Sneakers",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb1"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 29.99,
    StockQuantity: 100,
    Description: "Comfortable sneakers for kids.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CS-001",
    IsActive: true,
    ProductType: "Sneakers",
    Brand: "Brand W",
    Color: "Blue",
    Size: "12",
    Featured: false,
  },
  {
    ProductName: "Children's Sandals",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb1"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 24.99,
    StockQuantity: 150,
    Description: "Lightweight sandals for summer.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CS-002",
    IsActive: true,
    ProductType: "Sandals",
    Brand: "Brand X",
    Color: "Pink",
    Size: "11",
    Featured: true,
  },
  {
    ProductName: "Children's Boots",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb1"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 39.99,
    StockQuantity: 80,
    Description: "Durable boots for kids.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "CB-001",
    IsActive: true,
    ProductType: "Boots",
    Brand: "Brand Y",
    Color: "Brown",
    Size: "10",
    Featured: false,
  },

  // Children's Toys Products
  {
    ProductName: "Building Blocks Set",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb2"), // Replace with actual SubcategoryID
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 39.99,
    StockQuantity: 200,
    Description: "A fun building blocks set for creative play.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "BBS-002",
    IsActive: true,
    ProductType: "Toy",
    Brand: "Brand A",
    Color: "Multicolor",
    Size: "N/A",
    Featured: true,
  },
  {
    ProductName: "Toy Kitchen Set",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb2"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 49.99,
    StockQuantity: 100,
    Description: "A complete kitchen set for pretend play.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "TKS-001",
    IsActive: true,
    ProductType: "Toy",
    Brand: "Brand B",
    Color: "Pink",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Stuffed Animal Toy",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb2"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 24.99,
    StockQuantity: 150,
    Description: "A soft and cuddly stuffed animal.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "SAT-002",
    IsActive: true,
    ProductType: "Toy",
    Brand: "Brand C",
    Color: "Brown",
    Size: "Medium",
    Featured: true,
  },
  {
    ProductName: "Toy Car Set",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb2"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 29.99,
    StockQuantity: 100,
    Description: "A set of toy cars for kids.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "TCS-002",
    IsActive: true,
    ProductType: "Toy",
    Brand: "Brand D",
    Color: "Red",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Puzzle Game",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb2"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 19.99,
    StockQuantity: 120,
    Description: "A fun and educational puzzle game for kids.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "PG-001",
    IsActive: true,
    ProductType: "Puzzle",
    Brand: "Brand E",
    Color: "Multicolor",
    Size: "N/A",
    Featured: true,
  },
  {
    ProductName: "Action Figure Set",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb2"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 34.99,
    StockQuantity: 80,
    Description: "A set of action figures for imaginative play.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "AFS-001",
    IsActive: true,
    ProductType: "Action Figure",
    Brand: "Brand F",
    Color: "Various",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Building Blocks Set",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb2"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 39.99,
    StockQuantity: 200,
    Description: "A fun building blocks set for creative play.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "BBS-001",
    IsActive: true,
    ProductType: "Toy",
    Brand: "Brand Z",
    Color: "Multicolor",
    Size: "N/A",
    Featured: false,
  },
  {
    ProductName: "Stuffed Animal Toy",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb2"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 19.99,
    StockQuantity: 150,
    Description: "A soft and cuddly stuffed animal.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "SAT-001",
    IsActive: true,
    ProductType: "Toy",
    Brand: "Brand AA",
    Color: "Brown",
    Size: "Medium",
    Featured: true,
  },
  {
    ProductName: "Toy Car Set",
    SubcategoryID: new ObjectId("67bd9c50cbd9d3cca6916fb2"),
    CategoryID: new ObjectId("67bd98339496c970d120eb6c"),
    Price: 29.99,
    StockQuantity: 100,
    Description: "A set of toy cars for kids.",
    ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
    SKU: "TCS-001",
    IsActive: true,
    ProductType: "Toy",
    Brand: "Brand AB",
    Color: "Red",
    Size: "N/A",
    Featured: false,
  },
];

// Function to seed products
const seedProducts = async () => {
  try {
    await Product.deleteMany({}); // Clear existing products
    const result = await Product.insertMany(products);
    console.log("Products seeded:", result);
  } catch (error) {
    console.error("Error seeding products:", error);
  } finally {
    mongoose.connection.close(); // Close the connection
  }
};

// Run the seeding function
seedProducts();