const mongoose = require("mongoose");
const Category = require("../models/Category"); // Adjust the path accordingly
const Subcategory = require("../models/Subcategory"); // Adjust the path accordingly
const Product = require("../models/Product"); // Adjust the path accordingly

// Connect to MongoDB
mongoose
  .connect("mongodb://localhost:27017/shopping-kart", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log("MongoDB connected");
    seedDatabase();
  })
  .catch((err) => {
    console.error("MongoDB connection error:", err);
  });

// Dummy categories data for Men, Women, and Children
const data = [
  {
    CategoryName: "Men",
    Description: "Clothing, shoes, and accessories for men.",
    ImageURL: "https://example.com/images/men.jpg",
    IsActive: true,
    subcategories: [
      {
        SubcategoryName: "Clothing",
        Description: "Men's clothing including shirts, pants, and jackets.",
        ImageURL: "https://example.com/images/men-clothing.jpg",
        IsActive: true,
        categories: [
          {
            ProductName: "Men's Dress Shirt",
            // Replace with actual SubcategoryID

            Price: 39.99,
            StockQuantity: 90,
            Description: "Formal dress shirt for business and events.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MDS-001",
            IsActive: true,
            ProductType: "Shirt",
            Brand: "Brand A",
            Color: "White",
            Size: "L",
            Featured: true,
          },
          {
            ProductName: "Men's Cargo Pants",

            Price: 49.99,
            StockQuantity: 70,
            Description: "Comfortable cargo pants with multiple pockets.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MCP-001",
            IsActive: true,
            ProductType: "Pants",
            Brand: "Brand B",
            Color: "Olive",
            Size: "M",
            Featured: false,
          },
          {
            ProductName: "Men's Sports Jacket",

            Price: 89.99,
            StockQuantity: 40,
            Description: "Stylish sports jacket for casual outings.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MSJ-001",
            IsActive: true,
            ProductType: "Jacket",
            Brand: "Brand C",
            Color: "Navy",
            Size: "L",
            Featured: true,
          },
          {
            ProductName: "Men's Casual Shirt",
            // Replace with actual SubcategoryID

            Price: 29.99,
            StockQuantity: 100,
            Description: "A comfortable casual shirt for men.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MCS-001",
            IsActive: true,
            ProductType: "Shirt",
            Brand: "Brand A",
            Color: "Blue",
            Size: "M",
            Featured: false,
          },
          {
            ProductName: "Men's Formal Pants",

            Price: 49.99,
            StockQuantity: 80,
            Description: "Stylish formal pants for office wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MFP-001",
            IsActive: true,
            ProductType: "Pants",
            Brand: "Brand B",
            Color: "Black",
            Size: "L",
            Featured: true,
          },
          {
            ProductName: "Men's Denim Jacket",

            Price: 59.99,
            StockQuantity: 50,
            Description: "Classic denim jacket for men.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MDJ-001",
            IsActive: true,
            ProductType: "Jacket",
            Brand: "Brand C",
            Color: "Dark Blue",
            Size: "M",
            Featured: false,
          },
          {
            ProductName: "Men's Sports Shorts",

            Price: 24.99,
            StockQuantity: 150,
            Description: "Comfortable sports shorts for men.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MSS-001",
            IsActive: true,
            ProductType: "Shorts",
            Brand: "Brand D",
            Color: "Gray",
            Size: "L",
            Featured: true,
          },
          {
            ProductName: "Men's Polo Shirt",

            Price: 34.99,
            StockQuantity: 120,
            Description: "Stylish polo shirt for casual outings.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MPS-001",
            IsActive: true,
            ProductType: "Shirt",
            Brand: "Brand K",
            Color: "Green",
            Size: "L",
            Featured: true,
          },
          {
            ProductName: "Men's Chinos",

            Price: 49.99,
            StockQuantity: 60,
            Description: "Comfortable chinos for everyday wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MC-001",
            IsActive: true,
            ProductType: "Pants",
            Brand: "Brand L",
            Color: "Beige",
            Size: "M",
            Featured: false,
          },
          {
            ProductName: "Men's Hoodie",

            Price: 39.99,
            StockQuantity: 80,
            Description: "Cozy hoodie for chilly days.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MH-001",
            IsActive: true,
            ProductType: "Hoodie",
            Brand: "Brand M",
            Color: "Black",
            Size: "L",
            Featured: true,
          },
        ],
      },
      {
        SubcategoryName: "Shoes",

        Description: "Men's shoes including sneakers, boots, and formal shoes.",
        ImageURL: "https://example.com/images/men-shoes.jpg",
        IsActive: true,
        categories: [
          {
            ProductName: "Men's Oxford Shoes",
            // Replace with actual SubcategoryID

            Price: 89.99,
            StockQuantity: 50,
            Description: "Classic Oxford shoes for formal occasions.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MOS-001",
            IsActive: true,
            ProductType: "Dress Shoes",
            Brand: "Brand A",
            Color: "Black",
            Size: "10",
            Featured: true,
          },
          {
            ProductName: "Men's Casual Loafers",

            Price: 59.99,
            StockQuantity: 70,
            Description: "Comfortable loafers for everyday wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MCL-001",
            IsActive: true,
            ProductType: "Loafers",
            Brand: "Brand B",
            Color: "Brown",
            Size: "11",
            Featured: false,
          },
          {
            ProductName: "Men's High-Top Sneakers",

            Price: 69.99,
            StockQuantity: 40,
            Description: "Stylish high-top sneakers for a trendy look.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MHTS-001",
            IsActive: true,
            ProductType: "Sneakers",
            Brand: "Brand C",
            Color: "Gray",
            Size: "9",
            Featured: true,
          },
          {
            ProductName: "Men's Slip-On Sneakers",

            Price: 49.99,
            StockQuantity: 60,
            Description: "Easy-to-wear slip-on sneakers for casual outings.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MSOS-001",
            IsActive: true,
            ProductType: "Sneakers",
            Brand: "Brand D",
            Color: "Navy",
            Size: "10",
            Featured: false,
          },
          {
            ProductName: "Men's Chelsea Boots",

            Price: 79.99,
            StockQuantity: 35,
            Description: "Classic Chelsea boots for a sophisticated look.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MCB-001",
            IsActive: true,
            ProductType: "Boots",
            Brand: "Brand D",
            Color: "Black",
            Size: "10",
            Featured: false,
          },
          {
            ProductName: "Men's Flip Flops",

            Price: 19.99,
            StockQuantity: 150,
            Description: "Comfortable flip flops for summer.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MFF-001",
            IsActive: true,
            ProductType: "Flip Flops",
            Brand: "Brand E",
            Color: "Blue",
            Size: "11",
            Featured: true,
          },
          {
            ProductName: "Men's Loafers",

            Price: 69.99,
            StockQuantity: 40,
            Description: "Elegant loafers for formal occasions.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "ML-001",
            IsActive: true,
            ProductType: "Loafers",
            Brand: "Brand N",
            Color: "Navy",
            Size: "10",
            Featured: false,
          },
          {
            ProductName: "Men's Hiking Boots",

            Price: 99.99,
            StockQuantity: 25,
            Description: "Durable hiking boots for outdoor adventures.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MHB-001",
            IsActive: true,
            ProductType: "Boots",
            Brand: "Brand O",
            Color: "Gray",
            Size: "11",
            Featured: true,
          },
          {
            ProductName: "Men's Running Shoes",

            Price: 59.99,
            StockQuantity: 50,
            Description: "Lightweight running shoes for men.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MRS-001",
            IsActive: true,
            ProductType: "Shoes",
            Brand: "Brand E",
            Color: "Black",
            Size: "10",
            Featured: true,
          },
          {
            ProductName: "Men's Leather Boots",

            Price: 89.99,
            StockQuantity: 30,
            Description: "Durable leather boots for men.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MLB-001",
            IsActive: true,
            ProductType: "Boots",
            Brand: "Brand F",
            Color: "Brown",
            Size: "11",
            Featured: false,
          },
          {
            ProductName: "Men's Casual Sneakers",

            Price: 49.99,
            StockQuantity: 70,
            Description: "Stylish casual sneakers for everyday wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MCS-002",
            IsActive: true,
            ProductType: "Sneakers",
            Brand: "Brand G",
            Color: "White",
            Size: "9",
            Featured: true,
          },
        ],
      },
      {
        SubcategoryName: "Accessories",

        Description: "Men's accessories including belts, watches, and wallets.",
        ImageURL: "https://example.com/images/men-accessories.jpg",
        IsActive: true,
        categories: [
          {
            ProductName: "Men's Messenger Bag",

            Price: 49.99,
            StockQuantity: 60,
            Description: "Stylish messenger bag for work and travel.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MMB-001",
            IsActive: true,
            ProductType: "Messenger Bag",
            Brand: "Brand F",
            Color: "Brown",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Scarf",

            Price: 24.99,
            StockQuantity: 100,
            Description: "Warm scarf for winter.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MS-002",
            IsActive: true,
            ProductType: "Scarf",
            Brand: "Brand G",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Beanie Hat",

            Price: 19.99,
            StockQuantity: 120,
            Description: "Warm beanie hat for cold weather.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MBH-001",
            IsActive: true,
            ProductType: "Beanie",
            Brand: "Brand H",
            Color: "Dark Gray",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Belt",

            Price: 24.99,
            StockQuantity: 200,
            Description: "Classic leather belt for men.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MB-001",
            IsActive: true,
            ProductType: "Belt",
            Brand: "Brand P",
            Color: "Black",
            Size: "M",
            Featured: false,
          },
          {
            ProductName: "Men's Backpack",

            Price: 59.99,
            StockQuantity: 50,
            Description: "Stylish and functional backpack for daily use.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MBK-001",
            IsActive: true,
            ProductType: "Backpack",
            Brand: "Brand Q",
            Color: "Black",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Beanie",

            Price: 19.99,
            StockQuantity: 150,
            Description: "Warm beanie for winter.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MB-002",
            IsActive: true,
            ProductType: "Beanie",
            Brand: "Brand R",
            Color: "Gray",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Cufflinks",

            Price: 29.99,
            StockQuantity: 100,
            Description: "Elegant cufflinks for formal wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MC-002",
            IsActive: true,
            ProductType: "Cufflinks",
            Brand: "Brand S",
            Color: "Silver",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Tie",

            Price: 19.99,
            StockQuantity: 200,
            Description: "Classic tie for formal occasions.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MT-001",
            IsActive: true,
            ProductType: "Tie",
            Brand: "Brand T",
            Color: "Navy",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Leather Wallet",

            Price: 39.99,
            StockQuantity: 150,
            Description: "A stylish leather wallet for men.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MLW-001",
            IsActive: true,
            ProductType: "Wallet",
            Brand: "Brand H",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Men's Wrist Watch",

            Price: 199.99,
            StockQuantity: 20,
            Description: "Elegant wrist watch for men.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MW-001",
            IsActive: true,
            ProductType: "Watch",
            Brand: "Brand I",
            Color: "Silver",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Men's Sunglasses",

            Price: 29.99,
            StockQuantity: 200,
            Description: "Stylish sunglasses for men.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "MS-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand J",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
    ],
  },
  {
    CategoryName: "Women",
    Description: "Clothing, shoes, and accessories for women.",
    ImageURL: "https://example.com/images/women.jpg",
    IsActive: true,
    subcategories: [
      {
        SubcategoryName: "Clothing",

        Description: "Women's clothing including dresses, tops, and skirts.",
        ImageURL: "https://example.com/images/women-clothing.jpg",
        IsActive: true,
        categories: [
          {
            ProductName: "Women's Blazer",
            // Replace with actual SubcategoryID

            Price: 79.99,
            StockQuantity: 50,
            Description: "Stylish blazer for a professional look.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WBZ-001",
            IsActive: true,
            ProductType: "Blazer",
            Brand: "Brand A",
            Color: "Navy",
            Size: "M",
            Featured: true,
          },
          {
            ProductName: "Women's Maxi Skirt",

            Price: 39.99,
            StockQuantity: 80,
            Description: "Flowy maxi skirt for summer outings.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WMS-001",
            IsActive: true,
            ProductType: "Skirt",
            Brand: "Brand B",
            Color: "Floral",
            Size: "L",
            Featured: false,
          },
          {
            ProductName: "Women's Tunic Dress",

            Price: 49.99,
            StockQuantity: 60,
            Description: "Comfortable tunic dress for casual wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WTD-001",
            IsActive: true,
            ProductType: "Dress",
            Brand: "Brand C",
            Color: "Red",
            Size: "S",
            Featured: true,
          },
          {
            ProductName: "Women's Cardigan Sweater",

            Price: 44.99,
            StockQuantity: 70,
            Description: "Cozy cardigan sweater for layering.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WCS-001",
            IsActive: true,
            ProductType: "Sweater",
            Brand: "Brand D",
            Color: "Gray",
            Size: "M",
            Featured: false,
          },
          {
            ProductName: "Women's Activewear Leggings",

            Price: 29.99,
            StockQuantity: 100,
            Description: "Comfortable leggings for workouts.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WAL-001",
            IsActive: true,
            ProductType: "Leggings",
            Brand: "Brand E",
            Color: "Black",
            Size: "L",
            Featured: true,
          },
          {
            ProductName: "Women's Summer Shorts",

            Price: 24.99,
            StockQuantity: 90,
            Description: "Lightweight shorts for hot weather.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WSS-002",
            IsActive: true,
            ProductType: "Shorts",
            Brand: "Brand F",
            Color: "Beige",
            Size: "M",
            Featured: false,
          },
          {
            ProductName: "Women's Tunic Top",
            // Replace with actual SubcategoryID

            Price: 34.99,
            StockQuantity: 100,
            Description: "Stylish tunic top for casual wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WTT-001",
            IsActive: true,
            ProductType: "Tunic",
            Brand: "Brand A",
            Color: "Coral",
            Size: "M",
            Featured: true,
          },
          {
            ProductName: "Women's Pencil Skirt",

            Price: 49.99,
            StockQuantity: 80,
            Description: "Elegant pencil skirt for office wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WPS-001",
            IsActive: true,
            ProductType: "Skirt",
            Brand: "Brand B",
            Color: "Black",
            Size: "L",
            Featured: false,
          },
          {
            ProductName: "Women's Kimono Jacket",

            Price: 39.99,
            StockQuantity: 60,
            Description: "Lightweight kimono jacket for layering.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WKJ-001",
            IsActive: true,
            ProductType: "Jacket",
            Brand: "Brand C",
            Color: "Floral",
            Size: "S",
            Featured: true,
          },
          {
            ProductName: "Women's Cardigan",

            Price: 49.99,
            StockQuantity: 80,
            Description: "Cozy cardigan for layering.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WC-001",
            IsActive: true,
            ProductType: "Cardigan",
            Brand: "Brand U",
            Color: "Gray",
            Size: "L",
            Featured: false,
          },
          {
            ProductName: "Women's Jumpsuit",

            Price: 59.99,
            StockQuantity: 50,
            Description: "Stylish jumpsuit for a chic look.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WJ-001",
            IsActive: true,
            ProductType: "Jumpsuit",
            Brand: "Brand V",
            Color: "Black",
            Size: "S",
            Featured: true,
          },
          {
            ProductName: "Women's Summer Dress",

            Price: 49.99,
            StockQuantity: 75,
            Description: "A stylish summer dress for women.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WSD-001",
            IsActive: true,
            ProductType: "Dress",
            Brand: "Brand K",
            Color: "Red",
            Size: "L",
            Featured: false,
          },
          {
            ProductName: "Women's Maxi Dress",

            Price: 59.99,
            StockQuantity: 50,
            Description: "Flowy maxi dress for summer outings.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WMD-001",
            IsActive: true,
            ProductType: "Dress",
            Brand: "Brand M",
            Color: "Floral",
            Size: "S",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Shoes",

        Description: "Women's shoes including heels, flats, and sandals.",
        ImageURL: "https://example.com/images/women-shoes.jpg",
        IsActive: true,
        categories: [
          {
            ProductName: "Women's Ankle Strap Heels",
            // Replace with actual SubcategoryID

            Price: 69.99,
            StockQuantity: 40,
            Description: "Elegant ankle strap heels for formal occasions.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WASH-001",
            IsActive: true,
            ProductType: "Heels",
            Brand: "Brand A",
            Color: "Black",
            Size: "8",
            Featured: true,
          },
          {
            ProductName: "Women's Platform Sandals",

            Price: 49.99,
            StockQuantity: 60,
            Description: "Stylish platform sandals for summer.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WPS-002",
            IsActive: true,
            ProductType: "Sandals",
            Brand: "Brand B",
            Color: "Tan",
            Size: "7",
            Featured: false,
          },
          {
            ProductName: "Women's Ballerina Flats",

            Price: 39.99,
            StockQuantity: 80,
            Description: "Comfortable ballerina flats for everyday wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WBF-001",
            IsActive: true,
            ProductType: "Flats",
            Brand: "Brand C",
            Color: "Navy",
            Size: "8",
            Featured: true,
          },
          {
            ProductName: "Women's Combat Boots",

            Price: 89.99,
            StockQuantity: 30,
            Description: "Stylish combat boots for a rugged look.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WCB-002",
            IsActive: true,
            ProductType: "Boots",
            Brand: "Brand D",
            Color: "Black",
            Size: "9",
            Featured: false,
          },
          {
            ProductName: "Women's Slip-On Sneakers",

            Price: 44.99,
            StockQuantity: 50,
            Description: "Easy-to-wear slip-on sneakers for casual outings.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WSS-003",
            IsActive: true,
            ProductType: "Sneakers",
            Brand: "Brand E",
            Color: "White",
            Size: "8",
            Featured: true,
          },
          {
            ProductName: "Women's Hiking Shoes",

            Price: 99.99,
            StockQuantity: 25,
            Description: "Durable hiking shoes for outdoor adventures.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WHS-001",
            IsActive: true,
            ProductType: "Hiking Shoes",
            Brand: "Brand F",
            Color: "Gray",
            Size: "9",
            Featured: false,
          },
          {
            ProductName: "Women's Wedge Sandals",

            Price: 59.99,
            StockQuantity: 50,
            Description: "Stylish wedge sandals for summer outings.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WWS-001",
            IsActive: true,
            ProductType: "Wedge Sandals",
            Brand: "Brand D",
            Color: "Tan",
            Size: "8",
            Featured: false,
          },
          {
            ProductName: "Women's Slip-On Sneakers",

            Price: 49.99,
            StockQuantity: 70,
            Description: "Comfortable slip-on sneakers for everyday wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WSS-001",
            IsActive: true,
            ProductType: "Sneakers",
            Brand: "Brand E",
            Color: "White",
            Size: "7",
            Featured: true,
          },
          {
            ProductName: "Women's Sandals",

            Price: 39.99,
            StockQuantity: 60,
            Description: "Comfortable sandals for summer.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WS-002",
            IsActive: true,
            ProductType: "Sandals",
            Brand: "Brand W",
            Color: "Tan",
            Size: "8",
            Featured: false,
          },
          {
            ProductName: "Women's Combat Boots",

            Price: 89.99,
            StockQuantity: 30,
            Description: "Stylish combat boots for a rugged look.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WCB-001",
            IsActive: true,
            ProductType: "Boots",
            Brand: "Brand X",
            Color: "Black",
            Size: "9",
            Featured: true,
          },
          {
            ProductName: "Women's Heels",

            Price: 79.99,
            StockQuantity: 40,
            Description: "Stylish heels for women.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WH-001",
            IsActive: true,
            IsActive: true,
            ProductType: "Heels",
            Brand: "Brand N",
            Color: "Black",
            Size: "8",
            Featured: false,
          },
          {
            ProductName: "Women's Flats",

            Price: 39.99,
            StockQuantity: 60,
            Description: "Comfortable flats for everyday wear.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WF-001",
            IsActive: true,
            ProductType: "Flats",
            Brand: "Brand O",
            Color: "Navy",
            Size: "7",
            Featured: true,
          },
          {
            ProductName: "Women's Ankle Boots",

            Price: 89.99,
            StockQuantity: 30,
            Description: "Chic ankle boots for women.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WAB-001",
            IsActive: true,
            ProductType: "Boots",
            Brand: "Brand P",
            Color: "Brown",
            Size: "8",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Accessories",

        Description:
          "Women's accessories including bags, jewelry, and scarves.",
        ImageURL: "https://example.com/images/women-accessories.jpg",
        IsActive: true,
        categories: [
          {
            ProductName: "Women's Sunglasses",

            Price: 29.99,
            StockQuantity: 150,
            Description: "Stylish sunglasses for sunny days.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WSG-001",
            IsActive: true,
            ProductType: "Sunglasses",
            Brand: "Brand AA",
            Color: "Black",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Watch",

            Price: 149.99,
            StockQuantity: 25,
            Description: "Elegant watch for women.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WW-001",
            IsActive: true,
            ProductType: "Watch",
            Brand: "Brand AB",
            Color: "Rose Gold",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Tote Bag",

            Price: 59.99,
            StockQuantity: 50,
            Description: "Stylish tote bag for everyday use.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WTB-001",
            IsActive: true,
            ProductType: "Tote Bag",
            Brand: "Brand Y",
            Color: "Beige",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Hair Accessories Set",

            Price: 14.99,
            StockQuantity: 200,
            Description: "A set of stylish hair accessories.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WHA-001",
            IsActive: true,
            ProductType: "Hair Accessories",
            Brand: "Brand Z",
            Color: "Multicolor",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Handbag",

            Price: 89.99,
            StockQuantity: 50,
            Description: "Stylish handbag for women.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WHB-001",
            IsActive: true,
            ProductType: "Handbag",
            Brand: "Brand Q",
            Color: "Brown",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Women's Scarf",

            Price: 19.99,
            StockQuantity: 200,
            Description: "Fashionable scarf for women.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WS-001",
            IsActive: true,
            ProductType: "Scarf",
            Brand: "Brand R",
            Color: "Pink",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Women's Jewelry Set",

            Price: 49.99,
            StockQuantity: 100,
            Description: "Elegant jewelry set for special occasions.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "WJS-001",
            IsActive: true,
            ProductType: "Jewelry",
            Brand: "Brand S",
            Color: "Gold",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
    ],
  },
  {
    CategoryName: "Children",
    Description: "Clothing, shoes, and accessories for children.",
    ImageURL: "https://example.com/images/children.jpg",
    IsActive: true,
    subcategories: [
      {
        SubcategoryName: "Clothing",

        Description:
          "Children's clothing including shirts, pants, and dresses.",
        ImageURL: "https://example.com/images/children-clothing.jpg",
        IsActive: true,
        categories: [
          {
            ProductName: "Children's Graphic T-Shirt",
            // Replace with actual SubcategoryID

            Price: 19.99,
            StockQuantity: 150,
            Description: "Fun graphic t-shirt for kids.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CGT-001",
            IsActive: true,
            ProductType: "T-Shirt",
            Brand: "Brand A",
            Color: "Blue",
            Size: "M",
            Featured: true,
          },
          {
            ProductName: "Children's Denim Jacket",

            Price: 49.99,
            StockQuantity: 80,
            Description: "Classic denim jacket for a stylish look.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CDJ-001",
            IsActive: true,
            ProductType: "Jacket",
            Brand: "Brand B",
            Color: "Light Blue",
            Size: "L",
            Featured: false,
          },
          {
            ProductName: "Children's Sweatpants",

            Price: 29.99,
            StockQuantity: 100,
            Description: "Comfortable sweatpants for playtime.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CSP-001",
            IsActive: true,
            ProductType: "Pants",
            Brand: "Brand C",
            Color: "Gray",
            Size: "S",
            Featured: true,
          },
          {
            ProductName: "Children's Summer Dress",

            Price: 34.99,
            StockQuantity: 70,
            Description: "Cute summer dress for girls.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CSD-001",
            IsActive: true,
            ProductType: "Dress",
            Brand: "Brand D",
            Color: "Pink",
            Size: "M",
            Featured: false,
          },
          {
            ProductName: "Children's Pajama Set",

            Price: 24.99,
            StockQuantity: 120,
            Description: "Cozy pajama set for a good night's sleep.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CPS-001",
            IsActive: true,
            ProductType: "Pajamas",
            Brand: "Brand E",
            Color: "Star Print",
            Size: "L",
            Featured: true,
          },
          {
            ProductName: "Children's Raincoat",

            Price: 39.99,
            StockQuantity: 50,
            Description: "Waterproof raincoat for rainy days.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CRC-001",
            IsActive: true,
            ProductType: "Raincoat",
            Brand: "Brand F",
            Color: "Yellow",
            Size: "S",
            Featured: false,
          },
          {
            ProductName: "Children's Hoodie",
            // Replace with actual SubcategoryID

            Price: 29.99,
            StockQuantity: 100,
            Description: "Cozy hoodie for kids.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CH-001",
            IsActive: true,
            ProductType: "Hoodie",
            Brand: "Brand A",
            Color: "Blue",
            Size: "M",
            Featured: true,
          },
          {
            ProductName: "Children's Overalls",

            Price: 39.99,
            StockQuantity: 80,
            Description: "Durable overalls for playtime.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CO-001",
            IsActive: true,
            ProductType: "Overalls",
            Brand: "Brand B",
            Color: "Denim",
            Size: "L",
            Featured: false,
          },
          {
            ProductName: "Children's Rain Jacket",

            Price: 34.99,
            StockQuantity: 60,
            Description: "Waterproof rain jacket for kids.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CRJ-001",
            IsActive: true,
            ProductType: "Jacket",
            Brand: "Brand C",
            Color: "Yellow",
            Size: "S",
            Featured: true,
          },
          {
            ProductName: "Children's T-Shirt",

            Price: 19.99,
            StockQuantity: 150,
            Description: "Comfortable t-shirt for kids.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CTS-001",
            IsActive: true,
            ProductType: "T-Shirt",
            Brand: "Brand T",
            Color: "Green",
            Size: "S",
            Featured: false,
          },
          {
            ProductName: "Children's Jacket",

            Price: 39.99,
            StockQuantity: 80,
            Description: "Warm jacket for children.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CJ-001",
            IsActive: true,
            ProductType: "Jacket",
            Brand: "Brand U",
            Color: "Red",
            Size: "M",
            Featured: true,
          },
          {
            ProductName: "Children's Dress",

            Price: 29.99,
            StockQuantity: 100,
            Description: "Cute dress for little girls.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CD-001",
            IsActive: true,
            ProductType: "Dress",
            Brand: "Brand V",
            Color: "Pink",
            Size: "L",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Shoes",

        Description: "Children's shoes including sneakers and sandals.",
        ImageURL: "https://example.com/images/children-shoes.jpg",
        IsActive: true,
        categories: [
          {
            ProductName: "Children's Rain Boots",

            Price: 34.99,
            StockQuantity: 60,
            Description: "Waterproof rain boots for wet weather.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CRB-001",
            IsActive: true,
            ProductType: "Rain Boots",
            Brand: "Brand C",
            Color: "Yellow",
            Size: "11",
            Featured: true,
          },
          {
            ProductName: "Children's Slip-On Shoes",

            Price: 29.99,
            StockQuantity: 70,
            Description: "Easy-to-wear slip-on shoes for everyday use.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CSOS-001",
            IsActive: true,
            ProductType: "Slip-On Shoes",
            Brand: "Brand E",
            Color: "Red",
            Size: "9",
            Featured: true,
          },
          {
            ProductName: "Children's Hiking Shoes",

            Price: 59.99,
            StockQuantity: 30,
            Description: "Durable hiking shoes for outdoor adventures.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CHS-001",
            IsActive: true,
            ProductType: "Hiking Shoes",
            Brand: "Brand F",
            Color: "Green",
            Size: "10",
            Featured: false,
          },
          {
            ProductName: "Children's Dress Shoes",

            Price: 49.99,
            StockQuantity: 40,
            Description: "Elegant dress shoes for special occasions.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CDS-001",
            IsActive: true,
            ProductType: "Dress Shoes",
            Brand: "Brand D",
            Color: "Black",
            Size: "10",
            Featured: false,
          },
          {
            ProductName: "Children's Waterproof Boots",

            Price: 59.99,
            StockQuantity: 30,
            Description: "Durable waterproof boots for outdoor play.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CWB-001",
            IsActive: true,
            ProductType: "Boots",
            Brand: "Brand E",
            Color: "Brown",
            Size: "11",
            Featured: true,
          },
          {
            ProductName: "Children's Sneakers",

            Price: 29.99,
            StockQuantity: 100,
            Description: "Comfortable sneakers for kids.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CS-001",
            IsActive: true,
            ProductType: "Sneakers",
            Brand: "Brand W",
            Color: "Blue",
            Size: "12",
            Featured: false,
          },
          {
            ProductName: "Children's Sandals",

            Price: 24.99,
            StockQuantity: 150,
            Description: "Lightweight sandals for summer.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CS-002",
            IsActive: true,
            ProductType: "Sandals",
            Brand: "Brand X",
            Color: "Pink",
            Size: "11",
            Featured: true,
          },
          {
            ProductName: "Children's Boots",

            Price: 39.99,
            StockQuantity: 80,
            Description: "Durable boots for kids.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "CB-001",
            IsActive: true,
            ProductType: "Boots",
            Brand: "Brand Y",
            Color: "Brown",
            Size: "10",
            Featured: false,
          },
        ],
      },
      {
        SubcategoryName: "Toys",

        Description: "Toys for children of all ages.",
        ImageURL: "https://example.com/images/children-toys.jpg",
        IsActive: true,
        categories: [
          {
            ProductName: "Building Blocks Set",
            // Replace with actual SubcategoryID

            Price: 39.99,
            StockQuantity: 200,
            Description: "A fun building blocks set for creative play.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "BBS-002",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand A",
            Color: "Multicolor",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Toy Kitchen Set",

            Price: 49.99,
            StockQuantity: 100,
            Description: "A complete kitchen set for pretend play.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "TKS-001",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand B",
            Color: "Pink",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Stuffed Animal Toy",

            Price: 24.99,
            StockQuantity: 150,
            Description: "A soft and cuddly stuffed animal.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "SAT-002",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand C",
            Color: "Brown",
            Size: "Medium",
            Featured: true,
          },
          {
            ProductName: "Toy Car Set",

            Price: 29.99,
            StockQuantity: 100,
            Description: "A set of toy cars for kids.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "TCS-002",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand D",
            Color: "Red",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Puzzle Game",

            Price: 19.99,
            StockQuantity: 120,
            Description: "A fun and educational puzzle game for kids.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "PG-001",
            IsActive: true,
            ProductType: "Puzzle",
            Brand: "Brand E",
            Color: "Multicolor",
            Size: "N/A",
            Featured: true,
          },
          {
            ProductName: "Action Figure Set",

            Price: 34.99,
            StockQuantity: 80,
            Description: "A set of action figures for imaginative play.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "AFS-001",
            IsActive: true,
            ProductType: "Action Figure",
            Brand: "Brand F",
            Color: "Various",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Building Blocks Set",

            Price: 39.99,
            StockQuantity: 200,
            Description: "A fun building blocks set for creative play.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "BBS-001",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand Z",
            Color: "Multicolor",
            Size: "N/A",
            Featured: false,
          },
          {
            ProductName: "Stuffed Animal Toy",

            Price: 19.99,
            StockQuantity: 150,
            Description: "A soft and cuddly stuffed animal.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "SAT-001",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand AA",
            Color: "Brown",
            Size: "Medium",
            Featured: true,
          },
          {
            ProductName: "Toy Car Set",

            Price: 29.99,
            StockQuantity: 100,
            Description: "A set of toy cars for kids.",
            ImageURLs: ["https://dummyimage.com/533x669/000/fff.jpg"],
            SKU: "TCS-001",
            IsActive: true,
            ProductType: "Toy",
            Brand: "Brand AB",
            Color: "Red",
            Size: "N/A",
            Featured: false,
          },
        ],
      },
    ],
  },
];

async function seedDatabase() {
  try {
    // Clear existing data
    await Category.deleteMany({});
    await Subcategory.deleteMany({});
    await Product.deleteMany({});

    // Loop through each category
    for (const categoryData of data) {
      const category = new Category({
        CategoryName: categoryData.CategoryName,
        Description: categoryData.Description,
        ImageURL: categoryData.ImageURL,
        IsActive: categoryData.IsActive,
      });

      // Save the category
      const savedCategory = await category.save();

      // Loop through each subcategory
      for (const subcategoryData of categoryData.subcategories) {
        const subcategory = new Subcategory({
          SubcategoryName: subcategoryData.SubcategoryName,
          CategoryID: savedCategory._id,
          Description: subcategoryData.Description,
          ImageURL: subcategoryData.ImageURL,
          IsActive: subcategoryData.IsActive,
        });

        // Save the subcategory
        const savedSubcategory = await subcategory.save();

        // Loop through each product
        for (const productData of subcategoryData.categories) {
          const product = new Product({
            ProductName: productData.ProductName,
            SubcategoryID: savedSubcategory._id,
            CategoryID: savedCategory._id,
            Price: productData.Price,
            StockQuantity: productData.StockQuantity,
            Description: productData.Description,
            ImageURLs: productData.ImageURLs,
            SKU: productData.SKU,
            IsActive: productData.IsActive,
            ProductType: productData.ProductType,
            Brand: productData.Brand,
            Color: productData.Color,
            Size: productData.Size,
            Featured: productData.Featured,
          });

          // Save the product
          await product.save();
        }
      }
    }

    console.log("Database seeded successfully");
    mongoose.connection.close();
  } catch (error) {
    console.error("Error seeding database:", error);
  }
}
